// @ts-nocheck
/* eslint-disable */
/* Generated by Framer Code, do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * title?: string // Title
 * onytvzs8Uk0Change?: any // onytvzs8Uk0Change
 * link?: string // Link
 * icon?: any // Icon
}} Props

 */
var __fcWindow = typeof window !== "undefined" ? window : undefined;
var __fcNavigator = typeof __fcWindow !== "undefined" ? navigator : undefined;
import { U7DJzcmrO_default } from "./chunks/chunk-HFGP4JLG.js";
import { routes } from "./chunks/chunk-RUGFYN2D.js";

// virtual:cta-button
import { jsx } from "react/jsx-runtime";
import { Fragment } from "react";
import { ContextProviders } from "framercode";
import { WithFramerBreakpoints } from "framercode";
var locales = [];
var defaultResponsiveVariants = {};
var __fcPropMap = {
	title: "ytvzs8Uk0",
	link: "knrIa5hNz",
	icon: "AIYReRYlk",
};
function __fcProps(props) {
	const out = {
		...props,
	};
	for (const [readable, hashed] of Object.entries(__fcPropMap)) {
		if (readable in out) {
			if (!(hashed in out)) out[hashed] = out[readable];
			delete out[readable];
		}
	}
	return out;
}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"25ac7657c43786c597b8d10c8388d352e3a00cb0689038d46849444498792eea"
			}
			locale={locale}
			locales={locales}
		>
			<U7DJzcmrO_default suppressHydrationWarning={true} {...__fcProps(rest)} />
		</ContextProviders>
	);
}
/**
 * @type {import("framercode").Breakpoint}
 * Represents a responsive breakpoint for framercode.
 */

/**
 * @typedef VariantsMap
 * Partial record of Breakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in Breakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders CtaButtonFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"25ac7657c43786c597b8d10c8388d352e3a00cb0689038d46849444498792eea"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={U7DJzcmrO_default}
				variants={defaultResponsiveVariants}
				{...__fcProps(rest)}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, U7DJzcmrO_default);
var cta_button_default = ComponentWithRoot;
export { cta_button_default as default };
