// Generated by Framer Code, do not edit manually
import type * as React from 'react'

/**
 * Props are named after your Framer control titles. The original hashed
 * control ids (e.g. "b00pKBnWz") are also accepted at runtime; when both a
 * readable name and its hashed id are passed, the hashed value wins.
 */
export interface CtaButtonProps {
  title?: string; // Title
  onytvzs8Uk0Change?: any;
  link?: string; // Link
  icon?: any; // Icon
  children?: React.ReactNode;
  style?: React.CSSProperties;
  className?: string;
  id?: string;
  ref?: React.Ref<HTMLElement>;
  width?: number | string;
  height?: number | string;
  layoutId?: string;
  locale?: string;
}

export interface CtaButtonResponsiveProps extends Omit<CtaButtonProps, 'variant'> {
  variants?: Partial<Record<'base' | 'sm' | 'md' | 'lg' | 'xl' | '2xl', string>> & { base: string }
}

declare const CtaButton: React.ComponentType<CtaButtonProps> & {
  Responsive: React.ComponentType<CtaButtonResponsiveProps>
}

export default CtaButton
