// Generated by Framer Code, do not edit manually
import type * as React from 'react'

/**
 * Props are named after your Framer control titles. The original hashed
 * control ids (e.g. "b00pKBnWz") are also accepted at runtime; when both a
 * readable name and its hashed id are passed, the hashed value wins.
 */
export interface EngineDendritesProps {
  blue?: string; // Blue
  indigo?: string; // Indigo
  pink?: string; // Pink
  thickness?: number; // Thickness
  flowSpeed?: number; // Flow Speed
  glow?: number; // Glow
  intensity?: number; // Intensity
  children?: React.ReactNode;
  style?: React.CSSProperties;
  className?: string;
  id?: string;
  ref?: React.Ref<HTMLElement>;
  width?: number | string;
  height?: number | string;
  layoutId?: string;
  locale?: string;
}

export interface EngineDendritesResponsiveProps extends Omit<EngineDendritesProps, 'variant'> {
  variants?: Partial<Record<'base' | 'sm' | 'md' | 'lg' | 'xl' | '2xl', string>> & { base: string }
}

declare const EngineDendrites: React.ComponentType<EngineDendritesProps> & {
  Responsive: React.ComponentType<EngineDendritesResponsiveProps>
}

export default EngineDendrites
