// @ts-nocheck
/* eslint-disable */
/* Generated by Framer Code, do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * blue?: string // Blue
 * indigo?: string // Indigo
 * pink?: string // Pink
 * thickness?: number // Thickness
 * flowSpeed?: number // Flow Speed
 * glow?: number // Glow
 * intensity?: number // Intensity
}} Props

 */
var __fcWindow = typeof window !== "undefined" ? window : undefined;
var __fcNavigator = typeof __fcWindow !== "undefined" ? navigator : undefined;
import { routes } from "./chunks/chunk-RUGFYN2D.js";

// virtual:engine-dendrites
import { jsx } from "react/jsx-runtime";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useMemo, useRef, useState } from "react";
import {
	addPropertyControls,
	ControlType,
	useIsStaticRenderer,
} from "framercode";
function clamp(value, min, max) {
	return Math.max(min, Math.min(max, value));
}
function polarPoint(cx, cy, r, angle) {
	return {
		x: cx + Math.cos(angle) * r,
		y: cy + Math.sin(angle) * r,
	};
}
function buildRoute(id, cx, cy, r, target) {
	const dx = target.x - cx;
	const dy = target.y - cy;
	const dist = Math.max(1e-4, Math.sqrt(dx * dx + dy * dy));
	const ux = dx / dist;
	const uy = dy / dist;
	const ringPt = {
		x: cx + ux * r,
		y: cy + uy * r,
	};
	const trunkEnd = {
		x: cx + ux * (r + 18),
		y: cy + uy * (r + 18),
	};
	const cornerRadius = 8;
	const horizontal = Math.abs(dx) > Math.abs(dy);
	const nodes = [ringPt];
	let runPath = `M ${trunkEnd.x.toFixed(2)} ${trunkEnd.y.toFixed(2)}`;
	if (horizontal) {
		if (Math.abs(target.y - trunkEnd.y) < 1.5) {
			runPath += ` L ${target.x.toFixed(2)} ${target.y.toFixed(2)}`;
		} else {
			const yDir = target.y > trunkEnd.y ? 1 : -1;
			const xDir = target.x > trunkEnd.x ? 1 : -1;
			const verticalX = target.x - xDir * cornerRadius;
			runPath += ` L ${verticalX.toFixed(2)} ${trunkEnd.y.toFixed(2)}`;
			runPath += ` A ${cornerRadius} ${cornerRadius} 0 0 ${yDir > 0 ? 1 : 0} ${target.x.toFixed(2)} ${(trunkEnd.y + yDir * cornerRadius).toFixed(2)}`;
			runPath += ` L ${target.x.toFixed(2)} ${target.y.toFixed(2)}`;
			nodes.push(
				{
					x: verticalX,
					y: trunkEnd.y,
				},
				{
					x: target.x,
					y: trunkEnd.y + yDir * cornerRadius,
				},
			);
		}
	} else {
		if (Math.abs(target.x - trunkEnd.x) < 1.5) {
			runPath += ` L ${target.x.toFixed(2)} ${target.y.toFixed(2)}`;
		} else {
			const xDir = target.x > trunkEnd.x ? 1 : -1;
			const yDir = target.y > trunkEnd.y ? 1 : -1;
			const horizontalY = target.y - yDir * cornerRadius;
			runPath += ` L ${trunkEnd.x.toFixed(2)} ${horizontalY.toFixed(2)}`;
			runPath += ` A ${cornerRadius} ${cornerRadius} 0 0 ${xDir > 0 ? 1 : 0} ${(trunkEnd.x + xDir * cornerRadius).toFixed(2)} ${target.y.toFixed(2)}`;
			runPath += ` L ${target.x.toFixed(2)} ${target.y.toFixed(2)}`;
			nodes.push(
				{
					x: trunkEnd.x,
					y: horizontalY,
				},
				{
					x: trunkEnd.x + xDir * cornerRadius,
					y: target.y,
				},
			);
		}
	}
	nodes.push(target);
	const stubBase = {
		x: trunkEnd.x + (target.x - trunkEnd.x) * 0.55,
		y: trunkEnd.y + (target.y - trunkEnd.y) * 0.55,
	};
	const perp = {
		x: -uy,
		y: ux,
	};
	const stubTip = {
		x: stubBase.x + perp.x * 12,
		y: stubBase.y + perp.y * 12,
	};
	const stubPath = `M ${stubBase.x.toFixed(2)} ${stubBase.y.toFixed(2)} L ${stubTip.x.toFixed(2)} ${stubTip.y.toFixed(2)}`;
	return {
		id,
		ringPt,
		trunkEnd,
		runPath,
		trunkPath: `M ${ringPt.x.toFixed(2)} ${ringPt.y.toFixed(2)} L ${trunkEnd.x.toFixed(2)} ${trunkEnd.y.toFixed(2)}`,
		stubPath,
		nodes,
		stubTip,
	};
}
function EngineDendrites(props) {
	const {
		colorBlue = "#4F8CFF",
		colorIndigo = "#7B5CFF",
		colorPink = "#FF66B3",
		thickness = 1.3,
		flowSpeed = 1,
		glow = 2.5,
		intensity = 0.85,
	} = props;
	const rootRef = useRef(null);
	const dimsRef = useRef({
		w: 360,
		h: 360,
	});
	const [dims, setDims] = useState({
		w: 360,
		h: 360,
	});
	const isStatic = useIsStaticRenderer();
	const runRefs = useRef([]);
	const groupRefs = useRef([]);
	const rafRef = useRef(0);
	useEffect(() => {
		if (!rootRef.current || typeof __fcWindow === "undefined") return;
		const el = rootRef.current;
		const update = () => {
			const w = Math.max(1, Math.round(el.clientWidth));
			const h = Math.max(1, Math.round(el.clientHeight));
			dimsRef.current = {
				w,
				h,
			};
			setDims({
				w,
				h,
			});
		};
		update();
		const ro = new ResizeObserver(update);
		ro.observe(el);
		return () => ro.disconnect();
	}, []);
	const geometry = useMemo(() => {
		const w = dims.w;
		const h = dims.h;
		const cx = w / 2;
		const cy = h / 2;
		const r = Math.min(w, h) * 0.155;
		const mode = w > h * 1.4 ? "horizontal" : "vertical";
		const targets =
			mode === "horizontal"
				? [
						{
							x: w * 0.12,
							y: h * 0.22,
						},
						{
							x: w * 0.12,
							y: h * 0.5,
						},
						{
							x: w * 0.12,
							y: h * 0.78,
						},
						{
							x: w * 0.88,
							y: h * 0.22,
						},
						{
							x: w * 0.88,
							y: h * 0.5,
						},
						{
							x: w * 0.88,
							y: h * 0.78,
						},
					]
				: [
						{
							x: w * 0.22,
							y: h * 0.1,
						},
						{
							x: w * 0.5,
							y: h * 0.1,
						},
						{
							x: w * 0.78,
							y: h * 0.1,
						},
						{
							x: w * 0.22,
							y: h * 0.9,
						},
						{
							x: w * 0.5,
							y: h * 0.9,
						},
						{
							x: w * 0.78,
							y: h * 0.9,
						},
					];
		const routes2 = targets.map((target, i) =>
			buildRoute(`route-${i}`, cx, cy, r, target),
		);
		const pads = Array.from(
			{
				length: 18,
			},
			(_, i) => polarPoint(cx, cy, r + 2, (Math.PI * 2 * i) / 18),
		);
		return {
			w,
			h,
			cx,
			cy,
			r,
			routes: routes2,
			pads,
		};
	}, [dims]);
	useEffect(() => {
		if (isStatic || typeof __fcWindow === "undefined") return;
		const speed = clamp(flowSpeed, 0, 3);
		const animate = (ms) => {
			const time = ms * 1e-3;
			const dash = (-time * speed * 22) % 23;
			for (let i = 0; i < runRefs.current.length; i++) {
				const run = runRefs.current[i];
				if (run) run.style.strokeDashoffset = String(dash);
				const group = groupRefs.current[i];
				if (group) {
					group.style.opacity = String(
						intensity * (0.92 + 0.08 * Math.sin(time * 0.5 + i * 0.7)),
					);
				}
			}
			rafRef.current = __fcWindow.requestAnimationFrame(animate);
		};
		rafRef.current = __fcWindow.requestAnimationFrame(animate);
		return () => __fcWindow.cancelAnimationFrame(rafRef.current);
	}, [flowSpeed, intensity, isStatic, geometry.routes.length]);
	const safeThickness = clamp(thickness, 0.5, 3);
	return (
		<div
			suppressHydrationWarning={true}
			ref={rootRef}
			style={{
				position: "relative",
				width: "100%",
				height: "100%",
				background: "transparent",
				pointerEvents: "none",
				overflow: "visible",
				zIndex: 0,
			}}
		>
			<svg
				suppressHydrationWarning={true}
				viewBox={`0 0 ${geometry.w} ${geometry.h}`}
				style={{
					position: "absolute",
					inset: 0,
					width: "100%",
					height: "100%",
					overflow: "visible",
				}}
			>
				<defs suppressHydrationWarning={true}>
					{
						/* @__PURE__ */ _jsxs("radialGradient", {
							suppressHydrationWarning: true,
							id: "ed-radial",
							gradientUnits: "userSpaceOnUse",
							cx: geometry.cx,
							cy: geometry.cy,
							r: Math.max(geometry.w, geometry.h) * 0.55,
							children: [
								<stop
									suppressHydrationWarning={true}
									offset={"0%"}
									stopColor={colorBlue}
								/>,
								<stop
									suppressHydrationWarning={true}
									offset={"44%"}
									stopColor={colorIndigo}
								/>,
								<stop
									suppressHydrationWarning={true}
									offset={"100%"}
									stopColor={colorPink}
								/>,
							],
						})
					}
					<filter
						suppressHydrationWarning={true}
						id={"ed-glow"}
						x={"-50%"}
						y={"-50%"}
						width={"200%"}
						height={"200%"}
					>
						{
							/* @__PURE__ */ _jsx("feGaussianBlur", {
								suppressHydrationWarning: true,
								stdDeviation: glow,
								result: "blur",
							})
						}
						{
							/* @__PURE__ */ _jsxs("feMerge", {
								suppressHydrationWarning: true,
								children: [
									/* @__PURE__ */ _jsx("feMergeNode", {
										suppressHydrationWarning: true,
										in: "blur",
									}),
									/* @__PURE__ */ _jsx("feMergeNode", {
										suppressHydrationWarning: true,
										in: "SourceGraphic",
									}),
								],
							})
						}
					</filter>
				</defs>
				<g suppressHydrationWarning={true} opacity={0.3}>
					{geometry.pads.map((p, i) => (
						<circle
							key={`pad-${i}`}
							suppressHydrationWarning={true}
							cx={p.x}
							cy={p.y}
							r={1.8}
							fill={"url(#ed-radial)"}
						/>
					))}
				</g>
				{geometry.routes.map((route, i) => (
					<g
						key={route.id}
						suppressHydrationWarning={true}
						ref={(el) => {
							groupRefs.current[i] = el;
						}}
						opacity={intensity}
						filter={"url(#ed-glow)"}
					>
						<path
							suppressHydrationWarning={true}
							d={route.trunkPath}
							fill={"none"}
							stroke={"url(#ed-radial)"}
							strokeWidth={safeThickness * 1.5}
							strokeLinecap={"round"}
							strokeLinejoin={"round"}
						/>
						<path
							suppressHydrationWarning={true}
							d={route.runPath}
							ref={(el) => {
								runRefs.current[i] = el;
							}}
							fill={"none"}
							stroke={"url(#ed-radial)"}
							strokeWidth={safeThickness}
							strokeLinecap={"round"}
							strokeLinejoin={"round"}
							strokeDasharray={"7 16"}
							strokeDashoffset={isStatic ? 0 : 0}
						/>
						<path
							suppressHydrationWarning={true}
							d={route.stubPath}
							fill={"none"}
							stroke={"url(#ed-radial)"}
							strokeWidth={safeThickness * 0.85}
							strokeLinecap={"round"}
							strokeLinejoin={"round"}
						/>
						{route.nodes.map((n, nIdx) => (
							<g
								key={`${route.id}-node-${nIdx}`}
								suppressHydrationWarning={true}
							>
								<circle
									suppressHydrationWarning={true}
									cx={n.x}
									cy={n.y}
									r={3}
									fill={"url(#ed-radial)"}
								/>
								<circle
									suppressHydrationWarning={true}
									cx={n.x}
									cy={n.y}
									r={4.5}
									fill={"none"}
									stroke={"url(#ed-radial)"}
									strokeWidth={0.8}
								/>
							</g>
						))}
						<circle
							suppressHydrationWarning={true}
							cx={route.stubTip.x}
							cy={route.stubTip.y}
							r={2.2}
							fill={"url(#ed-radial)"}
						/>
					</g>
				))}
			</svg>
		</div>
	);
}
addPropertyControls(EngineDendrites, {
	colorBlue: {
		type: ControlType.Color,
		title: "Blue",
		defaultValue: "#4F8CFF",
	},
	colorIndigo: {
		type: ControlType.Color,
		title: "Indigo",
		defaultValue: "#7B5CFF",
	},
	colorPink: {
		type: ControlType.Color,
		title: "Pink",
		defaultValue: "#FF66B3",
	},
	thickness: {
		type: ControlType.Number,
		title: "Thickness",
		min: 0.5,
		max: 3,
		step: 0.1,
		defaultValue: 1.3,
	},
	flowSpeed: {
		type: ControlType.Number,
		title: "Flow Speed",
		min: 0,
		max: 3,
		step: 0.1,
		defaultValue: 1,
	},
	glow: {
		type: ControlType.Number,
		title: "Glow",
		min: 0,
		max: 8,
		step: 0.5,
		defaultValue: 2.5,
	},
	intensity: {
		type: ControlType.Number,
		title: "Intensity",
		min: 0.1,
		max: 1,
		step: 0.05,
		defaultValue: 0.85,
	},
});
EngineDendrites.defaultProps = {
	width: 360,
	height: 360,
};
var __FramerMetadata__ = {
	exports: {
		default: {
			type: "reactComponent",
			name: "EngineDendrites",
			slots: [],
			annotations: {
				framerContractVersion: "1",
				framerSupportedLayoutHeight: "any-prefer-fixed",
				framerSupportedLayoutWidth: "any-prefer-fixed",
			},
		},
		__FramerMetadata__: {
			type: "variable",
		},
	},
};

// virtual:engine-dendrites
import { Fragment } from "react";
import { ContextProviders } from "framercode";
import { WithFramerBreakpoints } from "framercode";
var locales = [];
var defaultResponsiveVariants = {};
var __fcPropMap = {
	blue: "colorBlue",
	indigo: "colorIndigo",
	pink: "colorPink",
};
function __fcProps(props) {
	const out = {
		...props,
	};
	for (const [readable, hashed] of Object.entries(__fcPropMap)) {
		if (readable in out) {
			if (!(hashed in out)) out[hashed] = out[readable];
			delete out[readable];
		}
	}
	return out;
}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"25ac7657c43786c597b8d10c8388d352e3a00cb0689038d46849444498792eea"
			}
			locale={locale}
			locales={locales}
		>
			<EngineDendrites suppressHydrationWarning={true} {...__fcProps(rest)} />
		</ContextProviders>
	);
}
/**
 * @type {import("framercode").Breakpoint}
 * Represents a responsive breakpoint for framercode.
 */

/**
 * @typedef VariantsMap
 * Partial record of Breakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in Breakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders EngineDendritesFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"25ac7657c43786c597b8d10c8388d352e3a00cb0689038d46849444498792eea"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={EngineDendrites}
				variants={defaultResponsiveVariants}
				{...__fcProps(rest)}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, EngineDendrites);
var engine_dendrites_default = ComponentWithRoot;
export { engine_dendrites_default as default };
