// @ts-nocheck
/* eslint-disable */
/* Generated by Framer Code, do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
}} Props

 */
var __fcWindow = typeof window !== "undefined" ? window : undefined;
var __fcNavigator = typeof __fcWindow !== "undefined" ? navigator : undefined;
import { routes } from "./chunks/chunk-RUGFYN2D.js";

// virtual:postical
import { jsx } from "react/jsx-runtime";
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import {
	addFonts,
	cx,
	RichText,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCSS,
	withFX,
	withOptimizedAppearEffect,
} from "framercode";
import { LayoutGroup, motion, MotionConfigContext } from "framercode";
import * as React from "react";
import { useRef } from "react";
var MotionDivWithFXWithOptimizedAppearEffect = withOptimizedAppearEffect(
	withFX(motion.div),
);
var serializationHash = "framer-yKwbl";
var variantClassNames = {
	IVZNxCRBs: "framer-v-19koipm",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	delay: 0,
	duration: 2.6,
	ease: [0.45, 0, 0.55, 1],
	type: "tween",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 10,
};
var transition3 = {
	delay: 0.1,
	duration: 1,
	ease: [0.42, 0, 0.3, 1],
	type: "tween",
};
var animation1 = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 1,
	skewX: 0,
	skewY: 0,
	transition: transition3,
	x: 0,
	y: 0,
};
var animation2 = {
	opacity: 1e-3,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.96,
	skewX: 0,
	skewY: 0,
	x: 0,
	y: 30,
};
var Transition = ({ value, children }) => {
	const config = React.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var Variants = motion.create(React.Fragment);
var getProps = ({ height, id, width, ...props }) => {
	return {
		...props,
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const fallbackRef = useRef(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const { style, className, layoutId, variant, ...restProps } = getProps(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		defaultVariant: "IVZNxCRBs",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const sharedStyleClassNames = [];
	const scopingClassNames = cx(serializationHash, ...sharedStyleClassNames);
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion.div
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx(
							scopingClassNames,
							"framer-19koipm",
							className,
							classNames,
						)}
						data-framer-name={"Variant 1"}
						layoutDependency={layoutDependency}
						layoutId={"IVZNxCRBs"}
						ref={refBinding}
						style={{
							...style,
						}}
					>
						<MotionDivWithFXWithOptimizedAppearEffect
							suppressHydrationWarning={true}
							__framer__loop={animation}
							__framer__loopEffectEnabled={true}
							__framer__loopPauseOffscreen={true}
							__framer__loopRepeatDelay={0}
							__framer__loopRepeatType={"mirror"}
							__framer__loopTransition={transition2}
							__perspectiveFX={false}
							__smartComponentFX={true}
							__targetOpacity={1}
							animate={animation1}
							className={"framer-711xtj"}
							data-border={true}
							data-framer-appear-id={"711xtj"}
							data-framer-name={"iPhone"}
							initial={animation2}
							layoutDependency={layoutDependency}
							layoutId={"yLJiM1NYR"}
							optimized={true}
							style={{
								"--border-bottom-width": "1px",
								"--border-color": "rgba(255, 255, 255, 0.12)",
								"--border-left-width": "1px",
								"--border-right-width": "1px",
								"--border-style": "solid",
								"--border-top-width": "1px",
								background:
									"linear-gradient(155deg, rgb(35, 39, 46) 0%, rgb(14, 16, 20) 100%)",
								borderBottomLeftRadius: 54,
								borderBottomRightRadius: 54,
								borderTopLeftRadius: 54,
								borderTopRightRadius: 54,
								boxShadow:
									"0px 40px 90px 0px rgba(17, 17, 17, 0.28), 0px 10px 30px 0px rgba(17, 17, 17, 0.14), inset 0px 1px 0px 0px rgba(255, 255, 255, 0.18)",
							}}
						>
							<motion.div
								suppressHydrationWarning={true}
								className={"framer-vm6xev"}
								data-framer-name={"Screen"}
								layoutDependency={layoutDependency}
								layoutId={"XowyOXhn8"}
								style={{
									backgroundColor: "rgb(6, 8, 10)",
									borderBottomLeftRadius: 46,
									borderBottomRightRadius: 46,
									borderTopLeftRadius: 46,
									borderTopRightRadius: 46,
								}}
							>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-19qvd23"}
									layoutDependency={layoutDependency}
									layoutId={"AXuCtIL6G"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-vhdcci"}
										fonts={["GF;Datatype-500"]}
										layoutDependency={layoutDependency}
										layoutId={"QTg9MCUFh"}
										style={{
											"--extracted-r6o4lv": "#9FB0C4",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React.Fragment>
											<motion.p
												suppressHydrationWarning={true}
												dir={"auto"}
												style={{
													"--font-selector": "R0Y7RGF0YXR5cGUtNTAw",
													"--framer-font-family": '"Datatype", monospace',
													"--framer-font-size": "11px",
													"--framer-font-weight": "500",
													"--framer-letter-spacing": "0.14em",
													"--framer-text-color":
														"var(--extracted-r6o4lv, #9FB0C4)",
													"--framer-text-transform": "uppercase",
												}}
											>
												{"NeuroCheck"}
											</motion.p>
										</React.Fragment>
									</RichText>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-v4tguv"}
										layoutDependency={layoutDependency}
										layoutId={"sG5AvdfqE"}
									>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-9svaof"}
											layoutDependency={layoutDependency}
											layoutId={"lUrPNNX4V"}
											style={{
												backgroundColor: "rgb(82, 214, 165)",
												borderBottomLeftRadius: 100,
												borderBottomRightRadius: 100,
												borderTopLeftRadius: 100,
												borderTopRightRadius: 100,
											}}
										/>
										<RichText
											suppressHydrationWarning={true}
											__fromCanvasComponent={true}
											className={"framer-xn6lqb"}
											fonts={["GF;Datatype-500"]}
											layoutDependency={layoutDependency}
											layoutId={"qDvWol9fx"}
											style={{
												"--extracted-r6o4lv": "#52D6A5",
											}}
											verticalAlignment={"top"}
											withExternalLayout={true}
										>
											<React.Fragment>
												<motion.p
													suppressHydrationWarning={true}
													dir={"auto"}
													style={{
														"--font-selector": "R0Y7RGF0YXR5cGUtNTAw",
														"--framer-font-family": '"Datatype", monospace',
														"--framer-font-size": "11px",
														"--framer-font-weight": "500",
														"--framer-letter-spacing": "0.12em",
														"--framer-text-color":
															"var(--extracted-r6o4lv, #52D6A5)",
														"--framer-text-transform": "uppercase",
													}}
												>
													{"Scanning"}
												</motion.p>
											</React.Fragment>
										</RichText>
									</motion.div>
								</motion.div>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1rybglt"}
									data-framer-name={"Scan"}
									layoutDependency={layoutDependency}
									layoutId={"Xvnx_coAk"}
								>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-1lzztab"}
										data-border={true}
										layoutDependency={layoutDependency}
										layoutId={"thZvnwFYa"}
										style={{
											"--border-bottom-width": "1.5px",
											"--border-color": "rgba(79, 140, 255, 0.45)",
											"--border-left-width": "1.5px",
											"--border-right-width": "1.5px",
											"--border-style": "solid",
											"--border-top-width": "1.5px",
											background:
												"radial-gradient(60% 60% at 50% 38%, rgba(79, 140, 255, 0.1) 0%, rgba(79, 140, 255, 0) 70%)",
											borderBottomLeftRadius: "50%",
											borderBottomRightRadius: "50%",
											borderTopLeftRadius: "50%",
											borderTopRightRadius: "50%",
										}}
									/>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-10mwjo9"}
										layoutDependency={layoutDependency}
										layoutId={"D0iMXBIOV"}
										style={{
											backgroundColor: "rgba(79, 140, 255, 0.18)",
										}}
									/>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-1i4gca1"}
										layoutDependency={layoutDependency}
										layoutId={"A03IgymRM"}
										style={{
											backgroundColor: "rgba(79, 140, 255, 0.16)",
										}}
									/>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-15oa1ya"}
										layoutDependency={layoutDependency}
										layoutId={"f0lQJ0sEe"}
										style={{
											backgroundColor: "rgba(79, 140, 255, 0.14)",
										}}
									/>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-1m7mmck"}
										layoutDependency={layoutDependency}
										layoutId={"psV_mTU2t"}
										style={{
											background:
												"linear-gradient(90deg, rgba(79, 140, 255, 0) 0%, rgb(79, 140, 255) 50%, rgba(79, 140, 255, 0) 100%)",
											borderBottomLeftRadius: 2,
											borderBottomRightRadius: 2,
											borderTopLeftRadius: 2,
											borderTopRightRadius: 2,
											boxShadow: "0px 0px 12px 0px rgba(79, 140, 255, 0.7)",
										}}
									/>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-wn204f"}
										data-border={true}
										layoutDependency={layoutDependency}
										layoutId={"rE2Goi4rk"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color": "rgba(79, 140, 255, 0.3)",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
									>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-j1ddof"}
											data-border={true}
											layoutDependency={layoutDependency}
											layoutId={"n1r7zwSrB"}
											style={{
												"--border-bottom-width": "1.5px",
												"--border-color": "rgb(79, 140, 255)",
												"--border-left-width": "1.5px",
												"--border-right-width": "1.5px",
												"--border-style": "solid",
												"--border-top-width": "1.5px",
												borderBottomLeftRadius: 100,
												borderBottomRightRadius: 100,
												borderTopLeftRadius: 100,
												borderTopRightRadius: 100,
											}}
										>
											<motion.div
												suppressHydrationWarning={true}
												className={"framer-zf8af5"}
												layoutDependency={layoutDependency}
												layoutId={"d7mmbTwSd"}
												style={{
													backgroundColor: "rgb(127, 178, 255)",
													borderBottomLeftRadius: 100,
													borderBottomRightRadius: 100,
													borderTopLeftRadius: 100,
													borderTopRightRadius: 100,
												}}
											/>
										</motion.div>
									</motion.div>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-2dl3xw"}
										data-border={true}
										layoutDependency={layoutDependency}
										layoutId={"e31HwglJI"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color": "rgba(79, 140, 255, 0.3)",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
									>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-rgv7me"}
											data-border={true}
											layoutDependency={layoutDependency}
											layoutId={"zi9axCVqQ"}
											style={{
												"--border-bottom-width": "1.5px",
												"--border-color": "rgb(79, 140, 255)",
												"--border-left-width": "1.5px",
												"--border-right-width": "1.5px",
												"--border-style": "solid",
												"--border-top-width": "1.5px",
												borderBottomLeftRadius: 100,
												borderBottomRightRadius: 100,
												borderTopLeftRadius: 100,
												borderTopRightRadius: 100,
											}}
										>
											<motion.div
												suppressHydrationWarning={true}
												className={"framer-q8abp5"}
												layoutDependency={layoutDependency}
												layoutId={"KTa0nV8Tm"}
												style={{
													backgroundColor: "rgb(127, 178, 255)",
													borderBottomLeftRadius: 100,
													borderBottomRightRadius: 100,
													borderTopLeftRadius: 100,
													borderTopRightRadius: 100,
												}}
											/>
										</motion.div>
									</motion.div>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-7mc97g"}
										layoutDependency={layoutDependency}
										layoutId={"GJue2XOme"}
										style={{
											backgroundColor: "rgba(127, 178, 255, 0.9)",
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
									/>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-19qjec4"}
										layoutDependency={layoutDependency}
										layoutId={"WfHHFetjO"}
										style={{
											backgroundColor: "rgba(82, 214, 165, 0.9)",
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
									/>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-iesjyv"}
										layoutDependency={layoutDependency}
										layoutId={"qpzre29aP"}
										style={{
											backgroundColor: "rgba(255, 255, 255, 0.8)",
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
									/>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-1dtn5b3"}
										layoutDependency={layoutDependency}
										layoutId={"lecBV9VtN"}
										style={{
											backgroundColor: "rgba(79, 140, 255, 0.9)",
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
									/>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-1h4p1ke"}
										layoutDependency={layoutDependency}
										layoutId={"AB6y0SwNd"}
										style={{
											backgroundColor: "rgba(127, 178, 255, 0.8)",
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
									/>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-1l594w8"}
										layoutDependency={layoutDependency}
										layoutId={"zEfDrThm7"}
										style={{
											backgroundColor: "rgba(255, 255, 255, 0.7)",
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
									/>
								</motion.div>
								<motion.div
									suppressHydrationWarning={true}
									className={"framer-1gq4o4f"}
									layoutDependency={layoutDependency}
									layoutId={"JlPBw2Ogj"}
								>
									<motion.div
										suppressHydrationWarning={true}
										className={"framer-6yvc2f"}
										data-border={true}
										layoutDependency={layoutDependency}
										layoutId={"fwjpj71E2"}
										style={{
											"--border-bottom-width": "1px",
											"--border-color": "rgba(255, 255, 255, 0.1)",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor: "rgba(255, 255, 255, 0.06)",
											borderBottomLeftRadius: 16,
											borderBottomRightRadius: 16,
											borderTopLeftRadius: 16,
											borderTopRightRadius: 16,
										}}
									>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-1u3w3xs"}
											layoutDependency={layoutDependency}
											layoutId={"xtHDfO8Jg"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-awhwnw"}
												fonts={["GF;Datatype-500"]}
												layoutDependency={layoutDependency}
												layoutId={"x9MeOOKmj"}
												style={{
													"--extracted-r6o4lv": "#9FB0C4",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														dir={"auto"}
														style={{
															"--font-selector": "R0Y7RGF0YXR5cGUtNTAw",
															"--framer-font-family": '"Datatype", monospace',
															"--framer-font-size": "10px",
															"--framer-font-weight": "500",
															"--framer-letter-spacing": "0.12em",
															"--framer-text-color":
																"var(--extracted-r6o4lv, #9FB0C4)",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"NRI\u2122 Score"}
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-23d7ei"}
												fonts={["Inter-SemiBold"]}
												layoutDependency={layoutDependency}
												layoutId={"Dg4ZkXogZ"}
												style={{
													"--extracted-r6o4lv": "#FFFFFF",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														dir={"auto"}
														style={{
															"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
															"--framer-font-size": "26px",
															"--framer-font-weight": "600",
															"--framer-letter-spacing": "-0.02em",
															"--framer-text-color":
																"var(--extracted-r6o4lv, #FFFFFF)",
														}}
													>
														{"87.4"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
										<motion.div
											suppressHydrationWarning={true}
											className={"framer-1iqeqps"}
											layoutDependency={layoutDependency}
											layoutId={"yZHFrZ4Bt"}
										>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-xq9l2o"}
												fonts={["GF;Datatype-500"]}
												layoutDependency={layoutDependency}
												layoutId={"HuDeHKXSm"}
												style={{
													"--extracted-r6o4lv": "#9FB0C4",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														dir={"auto"}
														style={{
															"--font-selector": "R0Y7RGF0YXR5cGUtNTAw",
															"--framer-font-family": '"Datatype", monospace',
															"--framer-font-size": "10px",
															"--framer-font-weight": "500",
															"--framer-letter-spacing": "0.12em",
															"--framer-text-color":
																"var(--extracted-r6o4lv, #9FB0C4)",
															"--framer-text-transform": "uppercase",
														}}
													>
														{"RTB"}
													</motion.p>
												</React.Fragment>
											</RichText>
											<RichText
												suppressHydrationWarning={true}
												__fromCanvasComponent={true}
												className={"framer-me6agx"}
												fonts={["Inter-SemiBold"]}
												layoutDependency={layoutDependency}
												layoutId={"fb9kwj8Cu"}
												style={{
													"--extracted-r6o4lv": "#52D6A5",
												}}
												verticalAlignment={"top"}
												withExternalLayout={true}
											>
												<React.Fragment>
													<motion.p
														suppressHydrationWarning={true}
														dir={"auto"}
														style={{
															"--font-selector": "SW50ZXItU2VtaUJvbGQ=",
															"--framer-font-size": "15px",
															"--framer-font-weight": "600",
															"--framer-letter-spacing": "-0.01em",
															"--framer-text-color":
																"var(--extracted-r6o4lv, #52D6A5)",
														}}
													>
														{"On track"}
													</motion.p>
												</React.Fragment>
											</RichText>
										</motion.div>
									</motion.div>
								</motion.div>
							</motion.div>
						</MotionDivWithFXWithOptimizedAppearEffect>
					</motion.div>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-yKwbl.framer-rzw8oa, .framer-yKwbl .framer-rzw8oa { display: block; }",
	".framer-yKwbl.framer-19koipm { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: min-content; justify-content: center; overflow: visible; padding: 0px; position: relative; width: 1120px; }",
	".framer-yKwbl .framer-711xtj { align-content: center; align-items: center; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 620px; justify-content: flex-start; overflow: visible; padding: 9px; position: relative; width: 300px; }",
	".framer-yKwbl .framer-vm6xev { align-content: center; align-items: center; display: flex; flex: 1 0 0px; flex-direction: column; flex-wrap: nowrap; gap: 0px; height: 1px; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; will-change: var(--framer-will-change-override, transform); }",
	".framer-yKwbl .framer-19qvd23 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; padding: 20px 20px 10px 20px; position: relative; width: 100%; }",
	".framer-yKwbl .framer-vhdcci, .framer-yKwbl .framer-xn6lqb, .framer-yKwbl .framer-awhwnw, .framer-yKwbl .framer-23d7ei, .framer-yKwbl .framer-xq9l2o, .framer-yKwbl .framer-me6agx { flex: none; height: auto; position: relative; white-space: pre; width: auto; }",
	".framer-yKwbl .framer-v4tguv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 6px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: min-content; }",
	".framer-yKwbl .framer-9svaof { flex: none; height: 6px; position: relative; width: 6px; }",
	".framer-yKwbl .framer-1rybglt { align-content: flex-start; align-items: flex-start; display: flex; flex: 1 0 0px; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 1px; justify-content: flex-start; overflow: var(--overflow-clip-fallback, clip); padding: 0px; position: relative; width: 100%; }",
	".framer-yKwbl .framer-1lzztab { flex: none; height: 210px; left: 62px; position: absolute; top: 40px; width: 158px; }",
	".framer-yKwbl .framer-10mwjo9 { flex: none; height: 1px; left: 74px; position: absolute; top: 110px; width: 134px; }",
	".framer-yKwbl .framer-1i4gca1 { flex: none; height: 1px; left: 80px; position: absolute; top: 185px; width: 122px; }",
	".framer-yKwbl .framer-15oa1ya { flex: none; height: 180px; left: 141px; position: absolute; top: 56px; width: 1px; }",
	".framer-yKwbl .framer-1m7mmck { flex: none; height: 2px; left: 56px; position: absolute; top: 150px; width: 170px; }",
	".framer-yKwbl .framer-wn204f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 40px; justify-content: center; left: 96px; padding: 0px; position: absolute; top: 128px; width: 40px; }",
	".framer-yKwbl .framer-j1ddof, .framer-yKwbl .framer-rgv7me { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 22px; justify-content: center; padding: 0px; position: relative; width: 22px; }",
	".framer-yKwbl .framer-zf8af5, .framer-yKwbl .framer-q8abp5 { flex: none; height: 7px; position: relative; width: 7px; }",
	".framer-yKwbl .framer-2dl3xw { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 0px; height: 40px; justify-content: center; left: 146px; padding: 0px; position: absolute; top: 128px; width: 40px; }",
	".framer-yKwbl .framer-7mc97g { flex: none; height: 4px; left: 70px; position: absolute; top: 70px; width: 4px; }",
	".framer-yKwbl .framer-19qjec4 { flex: none; height: 3px; left: 206px; position: absolute; top: 96px; width: 3px; }",
	".framer-yKwbl .framer-iesjyv { flex: none; height: 3px; left: 58px; position: absolute; top: 200px; width: 3px; }",
	".framer-yKwbl .framer-1dtn5b3 { flex: none; height: 4px; left: 214px; position: absolute; top: 210px; width: 4px; }",
	".framer-yKwbl .framer-1h4p1ke { flex: none; height: 3px; left: 120px; position: absolute; top: 246px; width: 3px; }",
	".framer-yKwbl .framer-1l594w8 { flex: none; height: 3px; left: 170px; position: absolute; top: 60px; width: 3px; }",
	".framer-yKwbl .framer-1gq4o4f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; padding: 14px 16px 18px 16px; position: relative; width: 100%; }",
	".framer-yKwbl .framer-6yvc2f { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; padding: 14px 16px 14px 16px; position: relative; width: 100%; }",
	".framer-yKwbl .framer-1u3w3xs { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: min-content; }",
	".framer-yKwbl .framer-1iqeqps { align-content: flex-end; align-items: flex-end; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 5px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: min-content; }",
	'.framer-yKwbl[data-border="true"]::after, .framer-yKwbl [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var FramerTQ6cK9smf = withCSS(Component, css, "framer-yKwbl");
var TQ6cK9smf_default = FramerTQ6cK9smf;
FramerTQ6cK9smf.displayName = "postical";
FramerTQ6cK9smf.defaultProps = {
	height: 620,
	width: 1120,
};
addFonts(
	FramerTQ6cK9smf,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Datatype",
					source: "google",
					style: "normal",
					uiFamilyName: "Datatype",
					url: "https://fonts.gstatic.com/s/datatype/v3/K2FcfZJQl-tDUlBEHaTYKmJIlpH1cGuNRqcCM4aUfKR9p6dHl5G8sz99u1eUcLE.woff2",
					weight: "500",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/hyOgCu0Xnghbimh0pE8QTvtt2AU.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/NeGmSOXrPBfEFIy5YZeHq17LEDA.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/oYaAX5himiTPYuN8vLWnqBbfD2s.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/lEJLP4R0yuCaMCjSXYHtJw72M.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/cRJyLNuTJR5jbyKzGi33wU9cqIQ.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/yDtI2UI8XcEg1W2je9XPN3Noo.woff2",
					weight: "600",
				},
				{
					cssFamilyName: "Inter",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/A0Wcc7NgXMjUuFdquHDrIZpzZw0.woff2",
					weight: "600",
				},
			],
		},
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
var __FramerMetadata__ = {
	exports: {
		default: {
			type: "reactComponent",
			name: "FramerTQ6cK9smf",
			slots: [],
			annotations: {
				framerDisplayContentsDiv: "false",
				framerAutoSizeImages: "true",
				framerCanvasComponentVariantDetails:
					'{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]}}}',
				framerIntrinsicHeight: "620",
				framerContractVersion: "1",
				framerComponentViewportWidth: "true",
				framerColorSyntax: "true",
				framerIntrinsicWidth: "1120",
				framerImmutableVariables: "true",
			},
		},
		Props: {
			type: "tsType",
			annotations: {
				framerContractVersion: "1",
			},
		},
		__FramerMetadata__: {
			type: "variable",
		},
	},
};

// virtual:postical
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "framercode";
import { WithFramerBreakpoints } from "framercode";
var locales = [];
var defaultResponsiveVariants = {};
var __fcPropMap = {};
function __fcProps(props) {
	const out = {
		...props,
	};
	for (const [readable, hashed] of Object.entries(__fcPropMap)) {
		if (readable in out) {
			if (!(hashed in out)) out[hashed] = out[readable];
			delete out[readable];
		}
	}
	return out;
}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"25ac7657c43786c597b8d10c8388d352e3a00cb0689038d46849444498792eea"
			}
			locale={locale}
			locales={locales}
		>
			<TQ6cK9smf_default suppressHydrationWarning={true} {...__fcProps(rest)} />
		</ContextProviders>
	);
}
/**
 * @type {import("framercode").Breakpoint}
 * Represents a responsive breakpoint for framercode.
 */

/**
 * @typedef VariantsMap
 * Partial record of Breakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in Breakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders PosticalFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"25ac7657c43786c597b8d10c8388d352e3a00cb0689038d46849444498792eea"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={TQ6cK9smf_default}
				variants={defaultResponsiveVariants}
				{...__fcProps(rest)}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, TQ6cK9smf_default);
var postical_default = ComponentWithRoot;
export { postical_default as default };
