// Generated by Framer Code, do not edit manually
import type * as React from 'react'

/**
 * Props are named after your Framer control titles. The original hashed
 * control ids (e.g. "b00pKBnWz") are also accepted at runtime; when both a
 * readable name and its hashed id are passed, the hashed value wins.
 */
export interface PosticalProps {
  children?: React.ReactNode;
  style?: React.CSSProperties;
  className?: string;
  id?: string;
  ref?: React.Ref<HTMLElement>;
  width?: number | string;
  height?: number | string;
  layoutId?: string;
  locale?: string;
}

export interface PosticalResponsiveProps extends Omit<PosticalProps, 'variant'> {
  variants?: Partial<Record<'base' | 'sm' | 'md' | 'lg' | 'xl' | '2xl', string>> & { base: string }
}

declare const Postical: React.ComponentType<PosticalProps> & {
  Responsive: React.ComponentType<PosticalResponsiveProps>
}

export default Postical
