// @ts-nocheck
/* eslint-disable */
/* Generated by Framer Code, do not edit manually */
"use client";

/**
 * @typedef Locale
 * string
 */

/**
 * @typedef {{
 * children?: React.ReactNode
 * locale?: Locale
 * style?: React.CSSProperties
 * className?: string
 * id?: string
 * ref?: any
 * width?: any
 * height?: any
 * layoutId?: string
 * variant?: 'Desktop' | 'Phone' | 'Phone Open' // Variant
}} Props

 */
var __fcWindow = typeof window !== "undefined" ? window : undefined;
var __fcNavigator = typeof __fcWindow !== "undefined" ? navigator : undefined;
import { U7DJzcmrO_default } from "./chunks/chunk-HFGP4JLG.js";
import { routes } from "./chunks/chunk-RUGFYN2D.js";

// virtual:topbar
import { jsx } from "react/jsx-runtime";
import { jsx as _jsx } from "react/jsx-runtime";
import {
	addPropertyControls,
	ControlType,
	cx,
	motion,
	useSVGTemplate,
	withCSS,
} from "framercode";
import * as React from "react";
import { forwardRef } from "react";
var mask = "var(--framer-icon-mask)";
var Base = /* @__PURE__ */ forwardRef(function (props, ref) {
	return (
		<svg suppressHydrationWarning={true} {...props} ref={ref}>
			{props.children}
		</svg>
	);
});
var MotionSVG = motion.create(Base);
var SVG = /* @__PURE__ */ forwardRef((props, ref) => {
	const { animated, layoutId, children, ...rest } = props;
	return animated ? (
		<MotionSVG
			suppressHydrationWarning={true}
			{...rest}
			layoutId={layoutId}
			ref={ref}
		>
			{children}
		</MotionSVG>
	) : (
		<svg suppressHydrationWarning={true} {...rest} ref={ref}>
			{children}
		</svg>
	);
});
var svg =
	'<svg display="block" role="presentation" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M 0 0 L 4 4 L 0 8" fill="transparent" height="8px" id="KF8GySj6V" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(18 8)" width="4px"/><path d="M 0 0 L 20 0" fill="transparent" height="1px" id="HpxXBXHgb" stroke-dasharray="" stroke-linecap="round" stroke-linejoin="round" stroke-width="var(--js9iwy, 2)" stroke="var(--1m973uw, rgb(0,0,0))" transform="translate(2 12)" width="20px"/></svg>';
var getProps = ({ color, height, id, width, width1, ...props }) => {
	return {
		...props,
		JEeZYcamG: width1 ?? props.JEeZYcamG ?? 2,
		P_DcoRcrY: color ?? props.P_DcoRcrY ?? "rgb(0, 0, 0)",
	};
};
var Component = /* @__PURE__ */ React.forwardRef(function (props, ref) {
	const {
		style,
		className: className2,
		layoutId,
		variant,
		P_DcoRcrY,
		JEeZYcamG,
		...restProps
	} = getProps(props);
	const href = useSVGTemplate("2561462644", svg);
	return (
		<SVG
			suppressHydrationWarning={true}
			{...restProps}
			className={cx("framer-k8Hsy", className2)}
			layoutId={layoutId}
			ref={ref}
			role={"presentation"}
			style={{
				"--1m973uw": P_DcoRcrY,
				"--js9iwy": JEeZYcamG,
				...style,
			}}
			viewBox={"0 0 24 24"}
		>
			<use suppressHydrationWarning={true} href={href} />
		</SVG>
	);
});
var css = [
	`.framer-k8Hsy { -webkit-mask: ${mask}; aspect-ratio: 1; display: block; mask: ${mask}; width: 24px; }`,
];
var Icon = withCSS(Component, css, "framer-k8Hsy");
Icon.displayName = "Move Right";
var cTXV5RyQ5_default = Icon;
addPropertyControls(Icon, {
	P_DcoRcrY: {
		defaultValue: "rgb(0, 0, 0)",
		hidden: false,
		title: "Color",
		type: ControlType.Color,
	},
	JEeZYcamG: {
		defaultValue: 2,
		displayStepper: true,
		hidden: false,
		max: 16,
		min: 1,
		title: "Width",
		type: ControlType.Number,
	},
});
var __FramerMetadata__ = {
	exports: {
		default: {
			type: "reactComponent",
			name: "Icon",
			slots: [],
			annotations: {
				framerContractVersion: "1",
				framerVariables: '{"P_DcoRcrY":"color","JEeZYcamG":"width1"}',
				framerIntrinsicHeight: "24",
				framerSupportedLayoutHeight: "any-prefer-fixed",
				framerSupportedLayoutWidth: "any-prefer-fixed",
				framerIntrinsicWidth: "24",
				framerImmutableVariables: "true",
				framerVector:
					'{"name":"Move Right","color":{"type":"variable","value":"1m973uw"},"set":{"localId":"vectorSet/ZsiCCGPvG","id":"ZsiCCGPvG","moduleId":"Y7SpbVH16cWqMhj75z1M"}}',
			},
		},
		__FramerMetadata__: {
			type: "variable",
		},
	},
};
import { jsx as _jsx2, jsxs as _jsxs } from "react/jsx-runtime";
import { useEffect, useRef } from "react";
function easeOutCubic(t) {
	const v = Math.max(0, Math.min(1, t));
	return 1 - Math.pow(1 - v, 3);
}
function easeInOut(t) {
	const v = Math.max(0, Math.min(1, t));
	return v < 0.5 ? 4 * v * v * v : 1 - Math.pow(-2 * v + 2, 3) / 2;
}
function getChildIndex(element) {
	if (!element || !element.parentElement) return 0;
	return Array.prototype.indexOf.call(element.parentElement.children, element);
}
function observeOnce(element, onVisible, threshold = 0.35) {
	if (
		typeof __fcWindow === "undefined" ||
		typeof IntersectionObserver === "undefined"
	) {
		onVisible();
		return () => {};
	}
	let fired = false;
	const observer = new IntersectionObserver(
		(entries) => {
			const isIntersecting = entries[0]?.isIntersecting;
			if (isIntersecting && !fired) {
				fired = true;
				onVisible();
				observer.disconnect();
			}
		},
		{
			threshold,
		},
	);
	observer.observe(element);
	return () => observer.disconnect();
}
function withCountUp(Component3) {
	return function WithCountUp(props) {
		const wrapperRef = useRef(null);
		useEffect(() => {
			if (typeof __fcWindow === "undefined" || !wrapperRef.current) return;
			const wrapper = wrapperRef.current;
			let raf = 0;
			let teardownObserver = () => {};
			const walker = document.createTreeWalker(wrapper, NodeFilter.SHOW_TEXT);
			let textNode = null;
			while (walker.nextNode()) {
				const candidate = walker.currentNode;
				if (candidate.textContent && candidate.textContent.trim().length > 0) {
					textNode = candidate;
					break;
				}
			}
			if (!textNode) return;
			const original = textNode.textContent || "";
			const match = original.match(/-?\d+(\.\d+)?/);
			if (!match) return;
			const numericTarget = Number(match[0]);
			if (!Number.isFinite(numericTarget)) return;
			const decimals = (match[1] || "").replace(".", "").length;
			const duration = 1400;
			const start = () => {
				const startTime = performance.now();
				const prefix = original.slice(0, match.index || 0);
				const suffix = original.slice((match.index || 0) + match[0].length);
				const tick = (now) => {
					const progress = Math.min(1, (now - startTime) / duration);
					const eased = easeOutCubic(progress);
					const value = numericTarget * eased;
					textNode.textContent = `${prefix}${value.toFixed(decimals)}${suffix}`;
					if (progress < 1) {
						raf = __fcWindow.requestAnimationFrame(tick);
					} else {
						textNode.textContent = original;
					}
				};
				raf = __fcWindow.requestAnimationFrame(tick);
			};
			teardownObserver = observeOnce(wrapper, start, 0.35);
			return () => {
				__fcWindow.cancelAnimationFrame(raf);
				teardownObserver();
				if (textNode) textNode.textContent = original;
			};
		}, []);
		return (
			<div
				suppressHydrationWarning={true}
				ref={wrapperRef}
				style={{
					display: "inline-flex",
				}}
			>
				<Component3 suppressHydrationWarning={true} {...props} />
			</div>
		);
	};
}
function withBarFill(Component3) {
	return function WithBarFill(props) {
		const wrapperRef = useRef(null);
		const isStatic = typeof __fcWindow === "undefined";
		useEffect(() => {
			if (isStatic || !wrapperRef.current) return;
			const wrapper = wrapperRef.current;
			let raf = 0;
			const indexDelay = getChildIndex(wrapper) * 120;
			let teardownObserver = () => {};
			wrapper.style.transform = "scaleX(0)";
			wrapper.style.opacity = "1";
			const start = () => {
				const startTime = performance.now() + indexDelay;
				const duration = 900;
				const tick = (now) => {
					const progress = Math.min(
						1,
						Math.max(0, (now - startTime) / duration),
					);
					const eased = easeOutCubic(progress);
					wrapper.style.transform = `scaleX(${eased.toFixed(4)})`;
					if (progress < 1) raf = __fcWindow.requestAnimationFrame(tick);
				};
				raf = __fcWindow.requestAnimationFrame(tick);
			};
			teardownObserver = observeOnce(wrapper, start, 0.35);
			return () => {
				__fcWindow.cancelAnimationFrame(raf);
				teardownObserver();
			};
		}, [isStatic]);
		return (
			<div
				suppressHydrationWarning={true}
				ref={wrapperRef}
				style={{
					display: "block",
					width: "100%",
					height: "100%",
					transformOrigin: "left center",
					willChange: "transform",
					transform: isStatic ? "scaleX(1)" : "scaleX(0)",
				}}
			>
				<Component3 suppressHydrationWarning={true} {...props} />
			</div>
		);
	};
}
function withGrowUp(Component3) {
	return function WithGrowUp(props) {
		const wrapperRef = useRef(null);
		const shimmerRef = useRef(null);
		const isStatic = typeof __fcWindow === "undefined";
		useEffect(() => {
			if (isStatic || !wrapperRef.current) return;
			const wrapper = wrapperRef.current;
			let raf = 0;
			let shimmerRaf = 0;
			let teardownObserver = () => {};
			const indexDelay = getChildIndex(wrapper) * 90;
			wrapper.style.transform = "scaleY(0)";
			const startShimmer = () => {
				if (!shimmerRef.current) return;
				const shimmer = shimmerRef.current;
				const loop = (now) => {
					const cycle = ((now / 1e3) % 3.5) / 3.5;
					const y = 115 - cycle * 150;
					shimmer.style.transform = `translateY(${y.toFixed(2)}%)`;
					shimmerRaf = __fcWindow.requestAnimationFrame(loop);
				};
				shimmerRaf = __fcWindow.requestAnimationFrame(loop);
			};
			const start = () => {
				const startTime = performance.now() + indexDelay;
				const duration = 700;
				const tick = (now) => {
					const progress = Math.min(
						1,
						Math.max(0, (now - startTime) / duration),
					);
					const eased = easeOutCubic(progress);
					wrapper.style.transform = `scaleY(${eased.toFixed(4)})`;
					if (progress < 1) {
						raf = __fcWindow.requestAnimationFrame(tick);
					} else {
						startShimmer();
					}
				};
				raf = __fcWindow.requestAnimationFrame(tick);
			};
			teardownObserver = observeOnce(wrapper, start, 0.35);
			return () => {
				__fcWindow.cancelAnimationFrame(raf);
				__fcWindow.cancelAnimationFrame(shimmerRaf);
				teardownObserver();
			};
		}, [isStatic]);
		return (
			<div
				suppressHydrationWarning={true}
				ref={wrapperRef}
				style={{
					display: "block",
					width: "100%",
					height: "100%",
					transformOrigin: "bottom center",
					willChange: "transform",
					position: "relative",
					overflow: "hidden",
					transform: isStatic ? "scaleY(1)" : "scaleY(0)",
				}}
			>
				<Component3 suppressHydrationWarning={true} {...props} />
				{!isStatic && (
					<div
						suppressHydrationWarning={true}
						ref={shimmerRef}
						style={{
							position: "absolute",
							left: 0,
							right: 0,
							height: "30%",
							top: 0,
							pointerEvents: "none",
							opacity: 0.18,
							mixBlendMode: "screen",
							background:
								"linear-gradient(to top, rgba(255,255,255,0) 0%, rgba(255,255,255,0.34) 45%, rgba(255,255,255,0) 100%)",
							transform: "translateY(120%)",
						}}
					/>
				)}
			</div>
		);
	};
}
function withDrawLine(Component3) {
	return function WithDrawLine(props) {
		const wrapperRef = useRef(null);
		const isStatic = typeof __fcWindow === "undefined";
		useEffect(() => {
			if (isStatic || !wrapperRef.current) return;
			const wrapper = wrapperRef.current;
			let raf = 0;
			let teardownObserver = () => {};
			wrapper.style.transform = "scaleX(0)";
			const start = () => {
				const startTime = performance.now();
				const duration = 900;
				const tick = (now) => {
					const progress = Math.min(1, (now - startTime) / duration);
					const eased = easeOutCubic(progress);
					wrapper.style.transform = `scaleX(${eased.toFixed(4)})`;
					if (progress < 1) raf = __fcWindow.requestAnimationFrame(tick);
				};
				raf = __fcWindow.requestAnimationFrame(tick);
			};
			teardownObserver = observeOnce(wrapper, start, 0.35);
			return () => {
				__fcWindow.cancelAnimationFrame(raf);
				teardownObserver();
			};
		}, [isStatic]);
		return (
			<div
				suppressHydrationWarning={true}
				ref={wrapperRef}
				style={{
					display: "block",
					width: "100%",
					height: "100%",
					transformOrigin: "left center",
					willChange: "transform",
					transform: isStatic ? "scaleX(1)" : "scaleX(0)",
				}}
			>
				<Component3 suppressHydrationWarning={true} {...props} />
			</div>
		);
	};
}
function withLogoPulse(Component3) {
	return function WithLogoPulse(props) {
		const wrapperRef = useRef(null);
		const isStatic = typeof __fcWindow === "undefined";
		useEffect(() => {
			if (isStatic || !wrapperRef.current) return;
			const wrapper = wrapperRef.current;
			let raf = 0;
			const pulseInterval = 5e3;
			const pulseDuration = 500;
			const tick = (now) => {
				const cycle = now % pulseInterval;
				let scale = 1;
				let glow = 0;
				if (cycle < pulseDuration) {
					const t = cycle / pulseDuration;
					const wave = t < 0.5 ? easeInOut(t * 2) : easeInOut((1 - t) * 2);
					scale = 1 + wave * 0.16;
					glow = wave;
				}
				wrapper.style.transform = `scale(${scale.toFixed(4)})`;
				wrapper.style.filter = `drop-shadow(0 0 ${(2 + glow * 10).toFixed(2)}px rgba(79,140,255,${(glow * 0.45).toFixed(3)}))`;
				raf = __fcWindow.requestAnimationFrame(tick);
			};
			raf = __fcWindow.requestAnimationFrame(tick);
			return () => __fcWindow.cancelAnimationFrame(raf);
		}, [isStatic]);
		return (
			<div
				suppressHydrationWarning={true}
				ref={wrapperRef}
				style={{
					display: "inline-flex",
					transform: "scale(1)",
					filter: "drop-shadow(0 0 0px rgba(79,140,255,0))",
				}}
			>
				<Component3 suppressHydrationWarning={true} {...props} />
			</div>
		);
	};
}
function withNavScroll(Component3) {
	return function WithNavScroll(props) {
		const wrapperRef = useRef(null);
		const isStatic = typeof __fcWindow === "undefined";
		useEffect(() => {
			if (isStatic || !wrapperRef.current) return;
			const wrapper = wrapperRef.current;
			const apply = () => {
				const active = __fcWindow.scrollY > 16;
				wrapper.style.boxShadow = active
					? "0 12px 40px rgba(17,17,17,0.12)"
					: "0 0 0 rgba(17,17,17,0)";
				wrapper.style.backdropFilter = active ? "blur(6px)" : "blur(0px)";
				wrapper.style.webkitBackdropFilter = active ? "blur(6px)" : "blur(0px)";
				wrapper.style.transform = "translateY(0)";
			};
			apply();
			__fcWindow.addEventListener("scroll", apply, {
				passive: true,
			});
			return () => __fcWindow.removeEventListener("scroll", apply);
		}, [isStatic]);
		return (
			<div
				suppressHydrationWarning={true}
				ref={wrapperRef}
				style={{
					display: "block",
					width: "100%",
					transition:
						"box-shadow 0.3s ease, backdrop-filter 0.3s ease, -webkit-backdrop-filter 0.3s ease",
					boxShadow: "0 0 0 rgba(17,17,17,0)",
				}}
			>
				<Component3 suppressHydrationWarning={true} {...props} />
			</div>
		);
	};
}
var __FramerMetadata__2 = {
	exports: {
		withDrawLine: {
			type: "reactHoc",
			name: "withDrawLine",
			annotations: {
				framerContractVersion: "1",
			},
		},
		withCountUp: {
			type: "reactHoc",
			name: "withCountUp",
			annotations: {
				framerContractVersion: "1",
			},
		},
		withLogoPulse: {
			type: "reactHoc",
			name: "withLogoPulse",
			annotations: {
				framerContractVersion: "1",
			},
		},
		withNavScroll: {
			type: "reactHoc",
			name: "withNavScroll",
			annotations: {
				framerContractVersion: "1",
			},
		},
		withBarFill: {
			type: "reactHoc",
			name: "withBarFill",
			annotations: {
				framerContractVersion: "1",
			},
		},
		withGrowUp: {
			type: "reactHoc",
			name: "withGrowUp",
			annotations: {
				framerContractVersion: "1",
			},
		},
		__FramerMetadata__: {
			type: "variable",
		},
	},
};
import { fontStore } from "framercode";
fontStore.loadFonts([]);
var fonts = [
	{
		explicitInter: true,
		fonts: [],
	},
];
var css2 = [
	".framer-mSDZk .framer-styles-preset-1pv74li:not(.rich-text-wrapper), .framer-mSDZk .framer-styles-preset-1pv74li.rich-text-wrapper a { --framer-link-current-text-color: var(--token-226e5698-0b9f-4bdd-bb3a-1c6b9df512cc); --framer-link-hover-text-color: var(--token-a49317d6-5a2f-4f45-8d8f-c392f2b76c5b); --framer-link-text-color: var(--token-42e567ea-e91f-4268-80b9-a21e1d8d26b2); transition-delay: 0s; transition-duration: 0.2s; transition-property: color; transition-timing-function: cubic-bezier(0.44, 0, 0.56, 1); }",
];
var className = "framer-mSDZk";
var __FramerMetadata__3 = {
	exports: {
		fonts: {
			type: "variable",
			annotations: {
				framerContractVersion: "1",
			},
		},
		className: {
			type: "variable",
			annotations: {
				framerContractVersion: "1",
			},
		},
		css: {
			type: "variable",
			annotations: {
				framerContractVersion: "1",
			},
		},
		__FramerMetadata__: {
			type: "variable",
		},
	},
};
import { jsx as _jsx3, jsxs as _jsxs2 } from "react/jsx-runtime";
import {
	addFonts,
	addPropertyControls as addPropertyControls2,
	ComponentViewportProvider,
	ControlType as ControlType2,
	cx as cx2,
	forwardLoader,
	getFonts,
	getFontsFromSharedStyle,
	getLoadingLazyAtYPosition,
	Image as Image1,
	Link,
	RichText,
	SmartComponentScopedContainer,
	useActiveVariantCallback,
	useComponentViewport,
	useLocaleInfo,
	useVariantState,
	withCodeBoundaryForOverrides,
	withCSS as withCSS2,
} from "framercode";
import {
	LayoutGroup,
	motion as motion2,
	MotionConfigContext,
} from "framercode";
import * as React2 from "react";
import { useRef as useRef2 } from "react";
var Image1WithLogoPulse1lgfb0u = withCodeBoundaryForOverrides(Image1, {
	nodeId: "zSqPNDPGE",
	override: withLogoPulse,
	scopeId: "ei6_qLvX8",
});
var CTAButtonFonts = getFonts(U7DJzcmrO_default);
var cycleOrder = ["D2Mo9C1mB", "aomrkGkIH", "yAExP2dGl"];
var serializationHash = "framer-zhsAc";
var variantClassNames = {
	aomrkGkIH: "framer-v-2tou33",
	D2Mo9C1mB: "framer-v-nceepu",
	yAExP2dGl: "framer-v-7kwafg",
};
function addPropertyOverrides(overrides, ...variants) {
	const nextOverrides = {};
	variants?.forEach(
		(variant) => variant && Object.assign(nextOverrides, overrides[variant]),
	);
	return nextOverrides;
}
var transition1 = {
	bounce: 0.2,
	delay: 0,
	duration: 0.4,
	type: "spring",
};
var transition2 = {
	bounce: 0.3,
	delay: 0,
	duration: 0.35,
	type: "spring",
};
var animation = {
	opacity: 1,
	rotate: 0,
	rotateX: 0,
	rotateY: 0,
	scale: 0.9,
	skewX: 0,
	skewY: 0,
	transition: transition2,
};
var Transition = ({ value, children }) => {
	const config = React2.useContext(MotionConfigContext);
	const transition = value ?? config.transition;
	const contextValue = React2.useMemo(
		() => ({
			...config,
			transition,
		}),
		[JSON.stringify(transition)],
	);
	return (
		<MotionConfigContext.Provider
			suppressHydrationWarning={true}
			value={contextValue}
		>
			{children}
		</MotionConfigContext.Provider>
	);
};
var humanReadableVariantMap = {
	"Phone Open": "yAExP2dGl",
	Desktop: "D2Mo9C1mB",
	Phone: "aomrkGkIH",
};
var Variants = motion2.create(React2.Fragment);
var getProps2 = ({ height, id, width, ...props }) => {
	return {
		...props,
		variant:
			humanReadableVariantMap[props.variant] ?? props.variant ?? "D2Mo9C1mB",
	};
};
var createLayoutDependency = (props, variants) => {
	if (props.layoutDependency)
		return variants.join("-") + props.layoutDependency;
	return variants.join("-");
};
var Component2 = /* @__PURE__ */ React2.forwardRef(function (props, ref) {
	const fallbackRef = useRef2(null);
	const refBinding = ref ?? fallbackRef;
	const defaultLayoutId = React2.useId();
	const { activeLocale, setLocale } = useLocaleInfo();
	const componentViewport = useComponentViewport();
	const {
		style,
		className: className2,
		layoutId,
		variant,
		...restProps
	} = getProps2(props);
	const {
		baseVariant,
		classNames,
		clearLoadingGesture,
		gestureHandlers,
		gestureVariant,
		isLoading,
		setGestureState,
		setVariant,
		variants,
	} = useVariantState({
		cycleOrder,
		defaultVariant: "D2Mo9C1mB",
		ref: refBinding,
		variant,
		variantClassNames,
	});
	const layoutDependency = createLayoutDependency(props, variants);
	const { activeVariantCallback, delay } =
		useActiveVariantCallback(baseVariant);
	const onTap11fmjz0 = activeVariantCallback(async (...args) => {
		setVariant("yAExP2dGl");
	});
	const onTap8f7u07 = activeVariantCallback(async (...args) => {
		setVariant("aomrkGkIH");
	});
	const sharedStyleClassNames = [className];
	const scopingClassNames = cx2(serializationHash, ...sharedStyleClassNames);
	const isDisplayed = () => {
		if (["aomrkGkIH", "yAExP2dGl"].includes(baseVariant)) return false;
		return true;
	};
	const isDisplayed1 = () => {
		if (baseVariant === "aomrkGkIH") return true;
		return false;
	};
	const isDisplayed2 = () => {
		if (baseVariant === "yAExP2dGl") return true;
		return false;
	};
	return (
		<LayoutGroup
			suppressHydrationWarning={true}
			id={layoutId ?? defaultLayoutId}
		>
			<Variants
				suppressHydrationWarning={true}
				animate={variants}
				initial={false}
			>
				<Transition suppressHydrationWarning={true} value={transition1}>
					<motion2.nav
						suppressHydrationWarning={true}
						{...restProps}
						{...gestureHandlers}
						className={cx2(
							scopingClassNames,
							"framer-nceepu",
							className2,
							classNames,
						)}
						data-border={true}
						data-framer-name={"Desktop"}
						layoutDependency={layoutDependency}
						layoutId={"D2Mo9C1mB"}
						ref={refBinding}
						style={{
							"--border-bottom-width": "1px",
							"--border-color": "rgba(17, 17, 17, 0.06)",
							"--border-left-width": "1px",
							"--border-right-width": "1px",
							"--border-style": "solid",
							"--border-top-width": "1px",
							backdropFilter: "blur(32px)",
							background:
								"linear-gradient(180deg, rgba(255, 255, 255, 0.82) 0%, rgba(255, 255, 255, 0.55) 100%)",
							borderBottomLeftRadius: 100,
							borderBottomRightRadius: 100,
							borderTopLeftRadius: 100,
							borderTopRightRadius: 100,
							boxShadow:
								"0px 12px 40px 0px rgba(17, 17, 17, 0.1), inset 0px 1px 0px 0px rgba(255, 255, 255, 0.9)",
							WebkitBackdropFilter: "blur(32px)",
							...style,
						}}
						variants={{
							yAExP2dGl: {
								background:
									"linear-gradient(180deg, rgba(255, 255, 255, 0.92) 0%, rgba(255, 255, 255, 0.78) 100%)",
								borderBottomLeftRadius: 20,
								borderBottomRightRadius: 20,
								borderTopLeftRadius: 20,
								borderTopRightRadius: 20,
								boxShadow:
									"0px 16px 50px 0px rgba(17, 17, 17, 0.12), inset 0px 1px 0px 0px rgba(255, 255, 255, 0.9)",
							},
						}}
						{...addPropertyOverrides(
							{
								aomrkGkIH: {
									"data-framer-name": "Phone",
								},
								yAExP2dGl: {
									"data-framer-name": "Phone Open",
								},
							},
							baseVariant,
							gestureVariant,
						)}
					>
						<motion2.div
							suppressHydrationWarning={true}
							className={"framer-cenfam"}
							data-framer-name={"Bar"}
							layoutDependency={layoutDependency}
							layoutId={"IKz0NhonH"}
						>
							<Link
								suppressHydrationWarning={true}
								href={{
									webPageId: "augiA20Il",
								}}
								motionChild={true}
								nodeId={"HsaHWEyc0"}
								scopeId={"ei6_qLvX8"}
							>
								<motion2.a
									suppressHydrationWarning={true}
									className={"framer-anau95 framer-em3omx"}
									data-framer-name={"Logo"}
									layoutDependency={layoutDependency}
									layoutId={"HsaHWEyc0"}
								>
									<Image1WithLogoPulse1lgfb0u
										suppressHydrationWarning={true}
										background={{
											alt: "",
											fit: "fill",
											loading: getLoadingLazyAtYPosition(
												(componentViewport?.y || 0) + 12 + 0 + 88 + 0,
											),
											pixelHeight: 1320,
											pixelWidth: 1320,
											sizes: "24px",
											src: "https://framerusercontent.com/images/R5i8NRIfBgkzlhQ9j2zipu2x5s.png?width=1320&height=1320",
										}}
										className={"framer-1lgfb0u"}
										data-framer-name={"Logo Mark"}
										layoutDependency={layoutDependency}
										layoutId={"zSqPNDPGE"}
										style={{
											borderBottomLeftRadius: 6,
											borderBottomRightRadius: 6,
											borderTopLeftRadius: 6,
											borderTopRightRadius: 6,
										}}
										{...addPropertyOverrides(
											{
												aomrkGkIH: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) + 12 + 0 + 8 + 0,
														),
														pixelHeight: 1320,
														pixelWidth: 1320,
														sizes: "24px",
														src: "https://framerusercontent.com/images/R5i8NRIfBgkzlhQ9j2zipu2x5s.png?width=1320&height=1320",
													},
												},
												yAExP2dGl: {
													background: {
														alt: "",
														fit: "fill",
														loading: getLoadingLazyAtYPosition(
															(componentViewport?.y || 0) + 12 + 0 + 0 + 0,
														),
														pixelHeight: 1320,
														pixelWidth: 1320,
														sizes: "24px",
														src: "https://framerusercontent.com/images/R5i8NRIfBgkzlhQ9j2zipu2x5s.png?width=1320&height=1320",
													},
												},
											},
											baseVariant,
											gestureVariant,
										)}
									/>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-16jnaay"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"pXwUxco1x"}
										style={{
											"--extracted-2gg91v": '"opsz" 18, "wght" 600',
											"--extracted-r6o4lv":
												"var(--token-a49317d6-5a2f-4f45-8d8f-c392f2b76c5b)",
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												suppressHydrationWarning={true}
												dir={"auto"}
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTRMQ0FpZDJkb2RDSWdOakF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-size": "17px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 18, "wght" 600)',
													"--framer-letter-spacing": "-0.01em",
													"--framer-line-height": "1em",
													"--framer-text-color":
														"var(--extracted-r6o4lv, var(--token-a49317d6-5a2f-4f45-8d8f-c392f2b76c5b))",
												}}
											>
												{"Postictal"}
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.a>
							</Link>
							{isDisplayed() && (
								<motion2.div
									suppressHydrationWarning={true}
									className={"framer-zzv8cv"}
									data-framer-name={"Links"}
									layoutDependency={layoutDependency}
									layoutId={"IpK7uj7ch"}
								>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-148oddr"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"P3dflhX0Q"}
										style={{
											"--extracted-2gg91v": '"opsz" 14, "wght" 500',
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												suppressHydrationWarning={true}
												dir={"auto"}
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-size": "14px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 14, "wght" 500)',
													"--framer-line-height": "1em",
												}}
											>
												<Link
													suppressHydrationWarning={true}
													href={{
														hash: ":CAX1Yd6vj",
														webPageId: "augiA20Il",
													}}
													motionChild={true}
													nodeId={"P3dflhX0Q"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"ei6_qLvX8"}
													smoothScroll={true}
												>
													<motion2.a
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1pv74li"}
														data-styles-preset={"xEQjMrA7K"}
													>
														{"Platform"}
													</motion2.a>
												</Link>
											</motion2.p>
										</React2.Fragment>
									</RichText>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1b4j2ht"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"x6zbZM68n"}
										style={{
											"--extracted-2gg91v": '"opsz" 14, "wght" 500',
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												suppressHydrationWarning={true}
												dir={"auto"}
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-size": "14px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 14, "wght" 500)',
													"--framer-line-height": "1em",
												}}
											>
												<Link
													suppressHydrationWarning={true}
													href={{
														hash: ":hCbVfKZvV",
														webPageId: "augiA20Il",
													}}
													motionChild={true}
													nodeId={"x6zbZM68n"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"ei6_qLvX8"}
													smoothScroll={true}
												>
													<motion2.a
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1pv74li"}
														data-styles-preset={"xEQjMrA7K"}
													>
														{"RTB"}
													</motion2.a>
												</Link>
											</motion2.p>
										</React2.Fragment>
									</RichText>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1i97ipd"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"Zqyzq8Vwv"}
										style={{
											"--extracted-2gg91v": '"opsz" 14, "wght" 500',
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												suppressHydrationWarning={true}
												dir={"auto"}
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-size": "14px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 14, "wght" 500)',
													"--framer-line-height": "1em",
												}}
											>
												<Link
													suppressHydrationWarning={true}
													href={"https://app.postictal.org"}
													motionChild={true}
													nodeId={"Zqyzq8Vwv"}
													openInNewTab={true}
													relValues={[]}
													scopeId={"ei6_qLvX8"}
													smoothScroll={false}
												>
													<motion2.a
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1pv74li"}
														data-styles-preset={"xEQjMrA7K"}
													>
														{"Study"}
													</motion2.a>
												</Link>
											</motion2.p>
										</React2.Fragment>
									</RichText>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-1ar0f6q"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"kmn8tz7gD"}
										style={{
											"--extracted-2gg91v": '"opsz" 14, "wght" 500',
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												suppressHydrationWarning={true}
												dir={"auto"}
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-size": "14px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 14, "wght" 500)',
													"--framer-line-height": "1em",
												}}
											>
												<Link
													suppressHydrationWarning={true}
													href={{
														hash: ":I3zacrUbz",
														webPageId: "augiA20Il",
													}}
													motionChild={true}
													nodeId={"kmn8tz7gD"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"ei6_qLvX8"}
													smoothScroll={true}
												>
													<motion2.a
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1pv74li"}
														data-styles-preset={"xEQjMrA7K"}
													>
														{"Research"}
													</motion2.a>
												</Link>
											</motion2.p>
										</React2.Fragment>
									</RichText>
									<RichText
										suppressHydrationWarning={true}
										__fromCanvasComponent={true}
										className={"framer-39yz9a"}
										fonts={["Inter-Variable"]}
										layoutDependency={layoutDependency}
										layoutId={"mdariZ5NF"}
										style={{
											"--extracted-2gg91v": '"opsz" 14, "wght" 500',
										}}
										verticalAlignment={"top"}
										withExternalLayout={true}
									>
										<React2.Fragment>
											<motion2.p
												suppressHydrationWarning={true}
												dir={"auto"}
												style={{
													"--font-selector":
														"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTBMQ0FpZDJkb2RDSWdOVEF3",
													"--framer-font-family":
														'"Inter Variable", "Inter Variable Placeholder", sans-serif',
													"--framer-font-size": "14px",
													"--framer-font-variation-axes":
														'var(--extracted-2gg91v, "opsz" 14, "wght" 500)',
													"--framer-line-height": "1em",
												}}
											>
												<Link
													suppressHydrationWarning={true}
													href={"mailto:study@postictal.org"}
													motionChild={true}
													nodeId={"mdariZ5NF"}
													openInNewTab={false}
													relValues={[]}
													scopeId={"ei6_qLvX8"}
													smoothScroll={false}
												>
													<motion2.a
														suppressHydrationWarning={true}
														className={"framer-styles-preset-1pv74li"}
														data-styles-preset={"xEQjMrA7K"}
													>
														{"Contact"}
													</motion2.a>
												</Link>
											</motion2.p>
										</React2.Fragment>
									</RichText>
								</motion2.div>
							)}
							<motion2.div
								suppressHydrationWarning={true}
								className={"framer-g4sy8j"}
								data-framer-name={"Actions"}
								layoutDependency={layoutDependency}
								layoutId={"SSisTTCaY"}
							>
								{isDisplayed() && (
									<ComponentViewportProvider
										suppressHydrationWarning={true}
										height={200}
										y={(componentViewport?.y || 0) + 12 + 0 + 0 + 0}
									>
										<SmartComponentScopedContainer
											suppressHydrationWarning={true}
											className={"framer-1vep7te-container"}
											layoutDependency={layoutDependency}
											layoutId={"ojuAeOzBf-container"}
											nodeId={"ojuAeOzBf"}
											rendersWithMotion={true}
											scopeId={"ei6_qLvX8"}
										>
											<U7DJzcmrO_default
												suppressHydrationWarning={true}
												AIYReRYlk={cTXV5RyQ5_default}
												height={"100%"}
												id={"ojuAeOzBf"}
												knrIa5hNz={"https://app.postictal.org"}
												layoutId={"ojuAeOzBf"}
												width={"100%"}
												ytvzs8Uk0={"Join the Study"}
											/>
										</SmartComponentScopedContainer>
									</ComponentViewportProvider>
								)}
								{isDisplayed1() && (
									<motion2.div
										suppressHydrationWarning={true}
										className={"framer-15q3tok"}
										data-border={true}
										data-framer-name={"Menu"}
										data-highlight={true}
										layoutDependency={layoutDependency}
										layoutId={"NtAg9FCFD"}
										onTap={onTap11fmjz0}
										style={{
											"--border-bottom-width": "1px",
											"--border-color": "rgba(17, 17, 17, 0.1)",
											"--border-left-width": "1px",
											"--border-right-width": "1px",
											"--border-style": "solid",
											"--border-top-width": "1px",
											backgroundColor: "rgba(17, 17, 17, 0.04)",
											borderBottomLeftRadius: 100,
											borderBottomRightRadius: 100,
											borderTopLeftRadius: 100,
											borderTopRightRadius: 100,
										}}
										whileTap={animation}
									>
										<motion2.div
											suppressHydrationWarning={true}
											className={"framer-fgx22g"}
											layoutDependency={layoutDependency}
											layoutId={"WJ_GF5E4c"}
											style={{
												backgroundColor:
													"var(--token-a49317d6-5a2f-4f45-8d8f-c392f2b76c5b)",
												borderBottomLeftRadius: 2,
												borderBottomRightRadius: 2,
												borderTopLeftRadius: 2,
												borderTopRightRadius: 2,
											}}
										/>
										<motion2.div
											suppressHydrationWarning={true}
											className={"framer-bd9u4y"}
											layoutDependency={layoutDependency}
											layoutId={"mCNQ3qDPj"}
											style={{
												backgroundColor:
													"var(--token-a49317d6-5a2f-4f45-8d8f-c392f2b76c5b)",
												borderBottomLeftRadius: 2,
												borderBottomRightRadius: 2,
												borderTopLeftRadius: 2,
												borderTopRightRadius: 2,
											}}
										/>
									</motion2.div>
								)}
							</motion2.div>
						</motion2.div>
						{isDisplayed2() && (
							<motion2.div
								suppressHydrationWarning={true}
								className={"framer-1k3fod3"}
								data-framer-name={"Drawer"}
								layoutDependency={layoutDependency}
								layoutId={"Q3jxcQxJP"}
							>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-6l1uqr"}
									data-highlight={true}
									fonts={["Inter-Variable"]}
									layoutDependency={layoutDependency}
									layoutId={"OuSsRcKk0"}
									onTap={onTap8f7u07}
									style={{
										"--extracted-2gg91v": '"opsz" 16, "wght" 500',
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											suppressHydrationWarning={true}
											dir={"auto"}
											style={{
												"--font-selector":
													"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTJMQ0FpZDJkb2RDSWdOVEF3",
												"--framer-font-family":
													'"Inter Variable", "Inter Variable Placeholder", sans-serif',
												"--framer-font-variation-axes":
													'var(--extracted-2gg91v, "opsz" 16, "wght" 500)',
												"--framer-letter-spacing": "-0.01em",
												"--framer-line-height": "1.45em",
											}}
										>
											<Link
												suppressHydrationWarning={true}
												href={{
													hash: ":CAX1Yd6vj",
													webPageId: "augiA20Il",
												}}
												motionChild={true}
												nodeId={"OuSsRcKk0"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"ei6_qLvX8"}
												smoothScroll={true}
											>
												<motion2.a
													suppressHydrationWarning={true}
													className={"framer-styles-preset-1pv74li"}
													data-styles-preset={"xEQjMrA7K"}
												>
													{"Platform"}
												</motion2.a>
											</Link>
										</motion2.p>
									</React2.Fragment>
								</RichText>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-x4jj1l"}
									data-highlight={true}
									fonts={["Inter-Variable"]}
									layoutDependency={layoutDependency}
									layoutId={"kr3w6WFmR"}
									onTap={onTap8f7u07}
									style={{
										"--extracted-2gg91v": '"opsz" 16, "wght" 500',
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											suppressHydrationWarning={true}
											dir={"auto"}
											style={{
												"--font-selector":
													"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTJMQ0FpZDJkb2RDSWdOVEF3",
												"--framer-font-family":
													'"Inter Variable", "Inter Variable Placeholder", sans-serif',
												"--framer-font-variation-axes":
													'var(--extracted-2gg91v, "opsz" 16, "wght" 500)',
												"--framer-letter-spacing": "-0.01em",
												"--framer-line-height": "1.45em",
											}}
										>
											<Link
												suppressHydrationWarning={true}
												href={{
													hash: ":hCbVfKZvV",
													webPageId: "augiA20Il",
												}}
												motionChild={true}
												nodeId={"kr3w6WFmR"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"ei6_qLvX8"}
												smoothScroll={true}
											>
												<motion2.a
													suppressHydrationWarning={true}
													className={"framer-styles-preset-1pv74li"}
													data-styles-preset={"xEQjMrA7K"}
												>
													{"RTB"}
												</motion2.a>
											</Link>
										</motion2.p>
									</React2.Fragment>
								</RichText>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1hmj480"}
									data-highlight={true}
									fonts={["Inter-Variable"]}
									layoutDependency={layoutDependency}
									layoutId={"UiS8lSGE8"}
									onTap={onTap8f7u07}
									style={{
										"--extracted-2gg91v": '"opsz" 16, "wght" 500',
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											suppressHydrationWarning={true}
											dir={"auto"}
											style={{
												"--font-selector":
													"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTJMQ0FpZDJkb2RDSWdOVEF3",
												"--framer-font-family":
													'"Inter Variable", "Inter Variable Placeholder", sans-serif',
												"--framer-font-variation-axes":
													'var(--extracted-2gg91v, "opsz" 16, "wght" 500)',
												"--framer-letter-spacing": "-0.01em",
												"--framer-line-height": "1.45em",
											}}
										>
											<Link
												suppressHydrationWarning={true}
												href={"https://app.postictal.org"}
												motionChild={true}
												nodeId={"UiS8lSGE8"}
												openInNewTab={true}
												relValues={[]}
												scopeId={"ei6_qLvX8"}
												smoothScroll={false}
											>
												<motion2.a
													suppressHydrationWarning={true}
													className={"framer-styles-preset-1pv74li"}
													data-styles-preset={"xEQjMrA7K"}
												>
													{"Study"}
												</motion2.a>
											</Link>
										</motion2.p>
									</React2.Fragment>
								</RichText>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-yjd0de"}
									data-highlight={true}
									fonts={["Inter-Variable"]}
									layoutDependency={layoutDependency}
									layoutId={"wdJa_jPQi"}
									onTap={onTap8f7u07}
									style={{
										"--extracted-2gg91v": '"opsz" 16, "wght" 500',
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											suppressHydrationWarning={true}
											dir={"auto"}
											style={{
												"--font-selector":
													"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTJMQ0FpZDJkb2RDSWdOVEF3",
												"--framer-font-family":
													'"Inter Variable", "Inter Variable Placeholder", sans-serif',
												"--framer-font-variation-axes":
													'var(--extracted-2gg91v, "opsz" 16, "wght" 500)',
												"--framer-letter-spacing": "-0.01em",
												"--framer-line-height": "1.45em",
											}}
										>
											<Link
												suppressHydrationWarning={true}
												href={{
													hash: ":I3zacrUbz",
													webPageId: "augiA20Il",
												}}
												motionChild={true}
												nodeId={"wdJa_jPQi"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"ei6_qLvX8"}
												smoothScroll={true}
											>
												<motion2.a
													suppressHydrationWarning={true}
													className={"framer-styles-preset-1pv74li"}
													data-styles-preset={"xEQjMrA7K"}
												>
													{"Research"}
												</motion2.a>
											</Link>
										</motion2.p>
									</React2.Fragment>
								</RichText>
								<RichText
									suppressHydrationWarning={true}
									__fromCanvasComponent={true}
									className={"framer-1f8hyao"}
									data-highlight={true}
									fonts={["Inter-Variable"]}
									layoutDependency={layoutDependency}
									layoutId={"VyHmzZ2Uz"}
									onTap={onTap8f7u07}
									style={{
										"--extracted-2gg91v": '"opsz" 16, "wght" 500',
									}}
									verticalAlignment={"top"}
									withExternalLayout={true}
								>
									<React2.Fragment>
										<motion2.p
											suppressHydrationWarning={true}
											dir={"auto"}
											style={{
												"--font-selector":
													"SW50ZXItVmFyaWFibGVWRj1JbTl3YzNvaUlERTJMQ0FpZDJkb2RDSWdOVEF3",
												"--framer-font-family":
													'"Inter Variable", "Inter Variable Placeholder", sans-serif',
												"--framer-font-variation-axes":
													'var(--extracted-2gg91v, "opsz" 16, "wght" 500)',
												"--framer-letter-spacing": "-0.01em",
												"--framer-line-height": "1.45em",
											}}
										>
											<Link
												suppressHydrationWarning={true}
												href={"mailto:study@postictal.org"}
												motionChild={true}
												nodeId={"VyHmzZ2Uz"}
												openInNewTab={false}
												relValues={[]}
												scopeId={"ei6_qLvX8"}
												smoothScroll={false}
											>
												<motion2.a
													suppressHydrationWarning={true}
													className={"framer-styles-preset-1pv74li"}
													data-styles-preset={"xEQjMrA7K"}
												>
													{"Contact"}
												</motion2.a>
											</Link>
										</motion2.p>
									</React2.Fragment>
								</RichText>
							</motion2.div>
						)}
					</motion2.nav>
				</Transition>
			</Variants>
		</LayoutGroup>
	);
});
var css3 = [
	"@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }",
	".framer-zhsAc.framer-em3omx, .framer-zhsAc .framer-em3omx { display: block; }",
	".framer-zhsAc.framer-nceepu { align-content: center; align-items: center; display: flex; flex-direction: column; flex-wrap: nowrap; gap: 18px; height: min-content; justify-content: flex-start; overflow: visible; padding: 12px 20px 12px 20px; position: relative; width: 1100px; }",
	".framer-zhsAc .framer-cenfam { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; height: min-content; justify-content: space-between; padding: 0px; position: relative; width: 100%; }",
	".framer-zhsAc .framer-anau95 { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 9px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; text-decoration: none; width: min-content; }",
	".framer-zhsAc .framer-1lgfb0u { flex: none; height: 24px; position: relative; width: 24px; }",
	".framer-zhsAc .framer-16jnaay, .framer-zhsAc .framer-148oddr, .framer-zhsAc .framer-1b4j2ht, .framer-zhsAc .framer-1i97ipd, .framer-zhsAc .framer-1ar0f6q, .framer-zhsAc .framer-39yz9a { -webkit-user-select: none; flex: none; height: auto; position: relative; user-select: none; white-space: pre; width: auto; }",
	".framer-zhsAc .framer-zzv8cv { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 28px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: min-content; }",
	".framer-zhsAc .framer-g4sy8j { align-content: center; align-items: center; display: flex; flex: none; flex-direction: row; flex-wrap: nowrap; gap: 10px; height: min-content; justify-content: flex-start; padding: 0px; position: relative; width: min-content; }",
	".framer-zhsAc .framer-1vep7te-container { flex: none; height: auto; position: relative; width: auto; }",
	".framer-zhsAc .framer-15q3tok { align-content: center; align-items: center; cursor: pointer; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 5px; height: 40px; justify-content: center; padding: 0px; position: relative; width: 40px; will-change: var(--framer-will-change-effect-override, transform); }",
	".framer-zhsAc .framer-fgx22g, .framer-zhsAc .framer-bd9u4y { flex: none; height: 2px; position: relative; width: 16px; }",
	".framer-zhsAc .framer-1k3fod3 { align-content: flex-start; align-items: flex-start; display: flex; flex: none; flex-direction: column; flex-wrap: nowrap; gap: 4px; height: min-content; justify-content: flex-start; padding: 10px 0px 6px 0px; position: relative; width: 100%; }",
	".framer-zhsAc .framer-6l1uqr, .framer-zhsAc .framer-x4jj1l, .framer-zhsAc .framer-1hmj480, .framer-zhsAc .framer-yjd0de, .framer-zhsAc .framer-1f8hyao { -webkit-user-select: none; cursor: pointer; flex: none; height: auto; position: relative; user-select: none; white-space: pre-wrap; width: 100%; word-break: break-word; word-wrap: break-word; }",
	".framer-zhsAc.framer-v-2tou33.framer-nceepu, .framer-zhsAc.framer-v-7kwafg.framer-nceepu { width: 340px; }",
	".framer-zhsAc.framer-v-7kwafg .framer-g4sy8j { min-height: 45px; min-width: 150px; }",
	...css2,
	'.framer-zhsAc[data-border="true"]::after, .framer-zhsAc [data-border="true"]::after { content: ""; border-width: var(--border-top-width, 0) var(--border-right-width, 0) var(--border-bottom-width, 0) var(--border-left-width, 0); border-color: var(--border-color, none); border-style: var(--border-style, none); width: 100%; height: 100%; position: absolute; box-sizing: border-box; left: 0; top: 0; border-radius: inherit; corner-shape: inherit; pointer-events: none; }',
];
var Framerei6_qLvX8 = withCSS2(Component2, css3, "framer-zhsAc");
var ei6_qLvX8_default = Framerei6_qLvX8;
Framerei6_qLvX8.displayName = "Topbar";
Framerei6_qLvX8.defaultProps = {
	height: 69,
	width: 1100,
};
addPropertyControls2(Framerei6_qLvX8, {
	variant: {
		options: ["D2Mo9C1mB", "aomrkGkIH", "yAExP2dGl"],
		optionTitles: ["Desktop", "Phone", "Phone Open"],
		title: "Variant",
		type: ControlType2.Enum,
	},
});
var variationAxes = [
	{
		defaultValue: 14,
		maxValue: 32,
		minValue: 14,
		name: "Optical size",
		tag: "opsz",
	},
	{
		defaultValue: 400,
		maxValue: 900,
		minValue: 100,
		name: "Weight",
		tag: "wght",
	},
];
addFonts(
	Framerei6_qLvX8,
	[
		{
			explicitInter: true,
			fonts: [
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0460-052F, U+1C80-1C88, U+20B4, U+2DE0-2DFF, U+A640-A69F, U+FE2E-FE2F",
					url: "https://framerusercontent.com/assets/mYcqTSergLb16PdbJJQMl9ebYm4.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0301, U+0400-045F, U+0490-0491, U+04B0-04B1, U+2116",
					url: "https://framerusercontent.com/assets/ZRl8AlxwsX1m7xS1eJCiSPbztg.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+1F00-1FFF",
					url: "https://framerusercontent.com/assets/nhSQpBRqFmXNUBY2p5SENQ8NplQ.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange: "U+0370-03FF",
					url: "https://framerusercontent.com/assets/DYHjxG0qXjopUuruoacfl5SA.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0100-024F, U+0259, U+1E00-1EFF, U+2020, U+20A0-20AB, U+20AD-20CF, U+2113, U+2C60-2C7F, U+A720-A7FF",
					url: "https://framerusercontent.com/assets/s7NH6sl7w4NU984r5hcmo1tPSYo.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+2000-206F, U+2070, U+2074-207E, U+2080-208E, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD",
					url: "https://framerusercontent.com/assets/7lw0VWkeXrGYJT05oB3DsFy8BaY.woff2",
					variationAxes,
					weight: "400",
				},
				{
					cssFamilyName: "Inter Variable",
					source: "framer",
					style: "normal",
					uiFamilyName: "Inter",
					unicodeRange:
						"U+0102-0103, U+0110-0111, U+0128-0129, U+0168-0169, U+01A0-01A1, U+01AF-01B0, U+1EA0-1EF9, U+20AB",
					url: "https://framerusercontent.com/assets/wx5nfqEgOXnxuFaxB0Mn9OhmcZA.woff2",
					variationAxes,
					weight: "400",
				},
			],
		},
		...CTAButtonFonts,
		...getFontsFromSharedStyle(fonts),
	],
	{
		supportsExplicitInterCodegen: true,
	},
);
Framerei6_qLvX8.loader = {
	load: (props, context) => {
		const locale = context.locale;
		return Promise.allSettled([forwardLoader(U7DJzcmrO_default, {}, context)]);
	},
};
var __FramerMetadata__4 = {
	exports: {
		Props: {
			type: "tsType",
			annotations: {
				framerContractVersion: "1",
			},
		},
		default: {
			type: "reactComponent",
			name: "Framerei6_qLvX8",
			slots: [],
			annotations: {
				framerContractVersion: "1",
				framerComponentViewportWidth: "true",
				framerImmutableVariables: "true",
				framerDisplayContentsDiv: "false",
				framerIntrinsicWidth: "1100",
				framerColorSyntax: "true",
				framerCanvasComponentVariantDetails:
					'{"propertyName":"variant","data":{"default":{"layout":["fixed","auto"]},"aomrkGkIH":{"layout":["fixed","auto"]},"yAExP2dGl":{"layout":["fixed","auto"]}}}',
				framerIntrinsicHeight: "69",
				framerAutoSizeImages: "true",
			},
		},
		__FramerMetadata__: {
			type: "variable",
		},
	},
};

// virtual:topbar
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "framercode";
import { WithFramerBreakpoints } from "framercode";
var locales = [];
var defaultResponsiveVariants = {
	base: "aomrkGkIH",
	xl: "D2Mo9C1mB",
};
var __fcPropMap = {};
function __fcProps(props) {
	const out = {
		...props,
	};
	for (const [readable, hashed] of Object.entries(__fcPropMap)) {
		if (readable in out) {
			if (!(hashed in out)) out[hashed] = out[readable];
			delete out[readable];
		}
	}
	return out;
}
/** @type {function(Props): any} */
function ComponentWithRoot({ locale, ...rest }) {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"25ac7657c43786c597b8d10c8388d352e3a00cb0689038d46849444498792eea"
			}
			locale={locale}
			locales={locales}
		>
			{
				/* @__PURE__ */ jsx(ei6_qLvX8_default, {
					suppressHydrationWarning: true,
					...__fcProps(rest),
				})
			}
		</ContextProviders>
	);
}
/**
 * @type {import("framercode").Breakpoint}
 * Represents a responsive breakpoint for framercode.
 */

/**
 * @typedef VariantsMap
 * Partial record of Breakpoint to Props.variant, with a mandatory 'base' key.
 * { [key in Breakpoint]?: Props['variant'] } & { base: Props['variant'] }
 */

/**
 * Renders TopbarFramerComponent for all breakpoints with a variants map. Variant prop is inferred per breakpoint.
 * @function
 * @param {Omit<Props, 'variant'> & {variants?: VariantsMap}} props
 * @returns {any}
 */
ComponentWithRoot.Responsive = ({ locale = "", ...rest }) => {
	return (
		<ContextProviders
			suppressHydrationWarning={true}
			routes={routes}
			framerSiteId={
				"25ac7657c43786c597b8d10c8388d352e3a00cb0689038d46849444498792eea"
			}
			locale={locale}
			locales={locales}
		>
			<WithFramerBreakpoints
				suppressHydrationWarning={true}
				Component={ei6_qLvX8_default}
				variants={defaultResponsiveVariants}
				{...__fcProps(rest)}
			/>
		</ContextProviders>
	);
};
Object.assign(ComponentWithRoot, ei6_qLvX8_default);
var topbar_default = ComponentWithRoot;
export { topbar_default as default };
