// Generated by Framer Code, do not edit manually
import type * as React from 'react'

/**
 * Props are named after your Framer control titles. The original hashed
 * control ids (e.g. "b00pKBnWz") are also accepted at runtime; when both a
 * readable name and its hashed id are passed, the hashed value wins.
 */
export interface TopbarProps {
  variant?: 'Desktop' | 'Phone' | 'Phone Open'; // Variant
  children?: React.ReactNode;
  style?: React.CSSProperties;
  className?: string;
  id?: string;
  ref?: React.Ref<HTMLElement>;
  width?: number | string;
  height?: number | string;
  layoutId?: string;
  locale?: string;
}

export interface TopbarResponsiveProps extends Omit<TopbarProps, 'variant'> {
  variants?: Partial<Record<'base' | 'sm' | 'md' | 'lg' | 'xl' | '2xl', TopbarProps['variant']>> & { base: TopbarProps['variant'] }
}

declare const Topbar: React.ComponentType<TopbarProps> & {
  Responsive: React.ComponentType<TopbarResponsiveProps>
}

export default Topbar
