/* Generated by Framer Code, do not edit manually */
import './framercode/styles.css'
import CtaButtonFramerComponent from './framercode/cta-button'
import TopbarFramerComponent from './framercode/topbar'
import NeuroCheckSceneFramerComponent from './framercode/neuro-check-scene'
import EngineDendritesFramerComponent from './framercode/engine-dendrites'

export default function App() {
  return (
    <div className='flex flex-col items-center gap-3 bg-[white]'>
      <CtaButtonFramerComponent.Responsive
        link={"https://app.postictal.org"}
        title={"Join the Study"}
      />
      <CtaButtonFramerComponent.Responsive
        link={"https://app.postictal.org"}
        title={"Join the Study"}
      />
      <CtaButtonFramerComponent.Responsive
        link={"https://app.postictal.org"}
        title={"Join the Study"}
      />
      <TopbarFramerComponent.Responsive />
      <TopbarFramerComponent.Responsive />
      <TopbarFramerComponent.Responsive />
      <NeuroCheckSceneFramerComponent.Responsive
        accentColor={"rgb(79, 140, 255)"}
        bloomStrength={0.3}
        cyanColor={"rgb(127, 227, 255)"}
        healthColor={"rgb(52, 199, 89)"}
        idleSpeed={1}
        meshOpacity={0.72}
        showCards={true}
        showPanel={true}
        theme={"light"}
      />
      <EngineDendritesFramerComponent.Responsive
        blue={"rgb(79, 140, 255)"}
        indigo={"rgb(123, 92, 255)"}
        pink={"rgb(255, 102, 179)"}
        flowSpeed={1}
        glow={2.5}
        intensity={0.85}
        thickness={1.4}
      />
      <CtaButtonFramerComponent.Responsive
        link={"https://app.postictal.org"}
        title={"Join the Study"}
      />
      <NeuroCheckSceneFramerComponent.Responsive
        accentColor={"rgb(79, 140, 255)"}
        bloomStrength={0.3}
        cyanColor={"rgb(127, 227, 255)"}
        healthColor={"rgb(52, 199, 89)"}
        idleSpeed={1}
        meshOpacity={0.72}
        showCards={true}
        showPanel={true}
        theme={"light"}
      />
      <EngineDendritesFramerComponent.Responsive
        blue={"rgb(79, 140, 255)"}
        indigo={"rgb(123, 92, 255)"}
        pink={"rgb(255, 102, 179)"}
        flowSpeed={1}
        glow={2.5}
        intensity={0.85}
        thickness={1.4}
      />
      <CtaButtonFramerComponent.Responsive
        link={"https://app.postictal.org"}
        title={"Join the Study"}
      />
      <NeuroCheckSceneFramerComponent.Responsive
        accentColor={"rgb(79, 140, 255)"}
        bloomStrength={0.3}
        cyanColor={"rgb(127, 227, 255)"}
        healthColor={"rgb(52, 199, 89)"}
        idleSpeed={1}
        meshOpacity={0.72}
        showCards={true}
        showPanel={true}
        theme={"light"}
      />
      <EngineDendritesFramerComponent.Responsive
        blue={"rgb(79, 140, 255)"}
        indigo={"rgb(123, 92, 255)"}
        pink={"rgb(255, 102, 179)"}
        flowSpeed={1}
        glow={2.5}
        intensity={0.85}
        thickness={1.4}
      />
      <CtaButtonFramerComponent.Responsive
        link={"https://app.postictal.org"}
        title={"Join the Study"}
      />
      <CtaButtonFramerComponent.Responsive
        link={"https://app.postictal.org"}
        title={"Join the Study"}
      />
      <CtaButtonFramerComponent.Responsive
        link={"https://app.postictal.org"}
        title={"Join the Study"}
      />
      <CtaButtonFramerComponent.Responsive
        link={"https://app.postictal.org"}
        title={"Join the Study"}
      />
    </div>
  )
}
